/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Vendedor.Devoluciones;


import DAOs.ClienteDAO;
import DAOs.DetalleVentaDAO;
import DAOs.ProductoDAO;
import DAOs.UsuarioDAO;
import DAOs.VentaDAO;
import Modelos.EntidadCliente;
import Modelos.EntidadDetalleVenta;
import Modelos.EntidadProducto;
import Modelos.EntidadUsuario;
import Modelos.EntidadVenta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VendedorDevProducto extends javax.swing.JFrame {

    UsuarioDAO uDAO = new UsuarioDAO();
    EntidadUsuario eu = new EntidadUsuario();
    ClienteDAO cDAO = new ClienteDAO();
    EntidadCliente ec = new EntidadCliente();
    ProductoDAO pDAO = new ProductoDAO();
    EntidadProducto ep = new EntidadProducto();
    VentaDAO vDAO = new VentaDAO();
    EntidadVenta ev = new EntidadVenta();
    DetalleVentaDAO dvDAO = new DetalleVentaDAO();
    EntidadDetalleVenta edv = new EntidadDetalleVenta();
    DefaultTableModel modelo = new DefaultTableModel();
    public VendedorDevProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Devolución De Producto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldClienteNit = new javax.swing.JTextField();
        jTextFieldClienteNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldClienteApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldClienteTelefono = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductosVendidos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldIdVenta = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldProductoCodigo = new javax.swing.JTextField();
        jTextFieldProductoNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldProductoPrecio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldT6 = new javax.swing.JTextField();
        jSpinnerT6 = new javax.swing.JSpinner();
        jTextFieldT8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSpinnerT8 = new javax.swing.JSpinner();
        jTextFieldT10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSpinnerT10 = new javax.swing.JSpinner();
        jTextFieldT12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSpinnerT12 = new javax.swing.JSpinner();
        jTextFieldT14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSpinnerT14 = new javax.swing.JSpinner();
        jTextFieldT16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSpinnerT16 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldT18 = new javax.swing.JTextField();
        jSpinnerT18 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldT20 = new javax.swing.JTextField();
        jSpinnerT20 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldT22 = new javax.swing.JTextField();
        jSpinnerT22 = new javax.swing.JSpinner();
        jButtonRealizarCambio = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Devolucion.png"))); // NOI18N
        jLabel1.setText("DEVOLUCIÓN DE PRODUCTO");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("IDENTIFICACIÓN/NIT");

        jTextFieldClienteNit.setEditable(false);
        jTextFieldClienteNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteNitActionPerformed(evt);
            }
        });

        jTextFieldClienteNombre.setEditable(false);
        jTextFieldClienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteNombreActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOMBRE");

        jTextFieldClienteApellido.setEditable(false);
        jTextFieldClienteApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteApellidoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("APELLIDO");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TELPEFONO");

        jTextFieldClienteTelefono.setEditable(false);
        jTextFieldClienteTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldClienteNit, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jTextFieldClienteNombre)
                    .addComponent(jTextFieldClienteApellido)
                    .addComponent(jTextFieldClienteTelefono))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldClienteNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldClienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos de la venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTableProductosVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRE", "PRECIO"
            }
        ));
        jTableProductosVendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosVendidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductosVendidos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID VENTA");

        jTextFieldIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdVentaActionPerformed(evt);
            }
        });
        jTextFieldIdVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdVentaKeyTyped(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CÓDIGO");

        jTextFieldProductoCodigo.setEditable(false);
        jTextFieldProductoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductoCodigoActionPerformed(evt);
            }
        });

        jTextFieldProductoNombre.setEditable(false);
        jTextFieldProductoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductoNombreActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NOMBRE");

        jTextFieldProductoPrecio.setEditable(false);
        jTextFieldProductoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductoPrecioActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PRECIO");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("T6");

        jTextFieldT6.setEditable(false);

        jTextFieldT8.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("T8");

        jTextFieldT10.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("T10");

        jTextFieldT12.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("T12");

        jTextFieldT14.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("T14");

        jTextFieldT16.setEditable(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("T16");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("T18");

        jTextFieldT18.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("T20");

        jTextFieldT20.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("T22");

        jTextFieldT22.setEditable(false);

        jButtonRealizarCambio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRealizarCambio.setText("REALIZAR CAMBIO");
        jButtonRealizarCambio.setEnabled(false);
        jButtonRealizarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(16, 16, 16)
                                .addComponent(jTextFieldProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldProductoCodigo)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldT10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldT16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldT22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jButtonRealizarCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRealizarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jTextFieldT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jButtonVolver.setBackground(new java.awt.Color(255, 153, 153));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVolver.setText("VOLVER");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldClienteNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteNitActionPerformed

    private void jTextFieldClienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteNombreActionPerformed

    private void jTextFieldClienteApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteApellidoActionPerformed

    private void jTextFieldClienteTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteTelefonoActionPerformed

    private void jTextFieldIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdVentaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        buscarVenta();
     
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

        public void limpiarTabla(){
    
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
       public void buscarVenta(){
          
        
        if(jTextFieldIdVenta.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el ID de la venta en la caja de texto");
            jTextFieldIdVenta.requestFocus();
        }else{
            int idVenta = Integer.parseInt(jTextFieldIdVenta.getText());
            ev = vDAO.buscarPorIdEstado(idVenta);
            if (ev.getIdVenta()!= 0 ){
                //captura datos del cliente
                int idCliente = ev.getIdCliente();
                ec = cDAO.buscarPorId(idCliente);
                String nitCliente = ec.getNit();
                String nombreCliente = ec.getNombre();
                String apellidoCliente = ec.getApellido();
                String telefonoCliente = ec.getTelefono();
                jTextFieldClienteNit.setText(nitCliente);
                jTextFieldClienteNombre.setText(nombreCliente);
                jTextFieldClienteApellido.setText(apellidoCliente);
                jTextFieldClienteTelefono.setText(telefonoCliente);
                // fin datos clientes
                buscarDetalle();
                jTextFieldIdVenta.setEditable(false);
                jButtonBuscar.setEnabled(false);
            }else{
                 JOptionPane.showMessageDialog(this,"El ID de venta no existe o la venta no está activa");
                 jTextFieldIdVenta.requestFocus();
             }
        } 
    }
    
    public void buscarDetalle(){
        int idVenta = Integer.parseInt(jTextFieldIdVenta.getText());
        List <EntidadDetalleVenta> lista = dvDAO.listarPorIdVenta(idVenta);
        modelo = (DefaultTableModel)jTableProductosVendidos.getModel();
        Object[]ob = new Object[3];
        
        for (int i = 0; i < lista.size(); i++) {
           int idProducto = lista.get(i).getIdProducto();
           ep = pDAO.buscarPorId(idProducto);
           String codigoProducto = ep.getCodigo();
           String nombreProducto = ep.getNombre();
           double precio = ep.getPrecioVenta();
           ob[0] = codigoProducto;// codigo producto
           ob[1] = nombreProducto;// nombre producto
           ob[2] = precio;
           modelo.addRow(ob);
        }
        
    jTableProductosVendidos.setModel(modelo);
    }
    private void jTextFieldProductoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductoCodigoActionPerformed

    private void jTextFieldProductoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductoNombreActionPerformed

    private void jTextFieldProductoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductoPrecioActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        VendedorRealizarDevolucion abrir = new VendedorRealizarDevolucion();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed
    public void reiniciarCant(){
    jSpinnerT6.setValue(0);
    jSpinnerT8.setValue(0);
    jSpinnerT10.setValue(0);
    jSpinnerT12.setValue(0);
    jSpinnerT14.setValue(0);
    jSpinnerT16.setValue(0);
    jSpinnerT18.setValue(0);
    jSpinnerT20.setValue(0);
    jSpinnerT22.setValue(0);
 
    }
    private void jTableProductosVendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosVendidosMouseClicked
  reiniciarCant();
        
        
        int idVenta = Integer.parseInt(jTextFieldIdVenta.getText());
        int fila = jTableProductosVendidos.getSelectedRow();
        if (fila == -1){
             JOptionPane.showMessageDialog(this, "Debe seleccionar un producto de la tabla");
        }else{
            
            String productoCodigo = jTableProductosVendidos.getValueAt(fila, 0).toString();
            String productoNombre = jTableProductosVendidos.getValueAt(fila, 1).toString();
            String productoPrecio = jTableProductosVendidos.getValueAt(fila, 2).toString(); 
            
            jTextFieldProductoCodigo.setText(productoCodigo);
            jTextFieldProductoNombre.setText(productoNombre);
            jTextFieldProductoPrecio.setText(productoPrecio);
            
            ep = pDAO.buscar(productoCodigo);
            int idProducto = ep.getIdProducto();
            
            Object[] ob = new Object[2];
        
            ob[0]= idVenta;
            ob[1]= idProducto;
            
            edv = dvDAO.buscarDetalleEspecifico(ob);
            
            int T6 = edv.getT6();
            int T8 = edv.getT8();
            int T10 = edv.getT10();
            int T12 = edv.getT12();
            int T14 = edv.getT14();
            int T16 = edv.getT16();
            int T18 = edv.getT18();
            int T20 = edv.getT20();
            int T22 = edv.getT22();
            int sumaTallas = T6 + T8 + T10 +T12 + T14 + T16 +T18 + T20 + T22;
            
            if (sumaTallas == 0){
            JOptionPane.showMessageDialog(this, "De este producto no se pueden realizar más devoluciones");
            jButtonRealizarCambio.setEnabled(false);
            
            jTextFieldT6.setText(String.valueOf(T6));
            jTextFieldT8.setText(String.valueOf(T8));
            jTextFieldT10.setText(String.valueOf(T10));
            jTextFieldT12.setText(String.valueOf(T12));
            jTextFieldT14.setText(String.valueOf(T14));
            jTextFieldT16.setText(String.valueOf(T16));
            jTextFieldT18.setText(String.valueOf(T18));
            jTextFieldT20.setText(String.valueOf(T20));
            jTextFieldT22.setText(String.valueOf(T22));
            
            }else{
                
            jTextFieldT6.setText(String.valueOf(T6));
            jTextFieldT8.setText(String.valueOf(T8));
            jTextFieldT10.setText(String.valueOf(T10));
            jTextFieldT12.setText(String.valueOf(T12));
            jTextFieldT14.setText(String.valueOf(T14));
            jTextFieldT16.setText(String.valueOf(T16));
            jTextFieldT18.setText(String.valueOf(T18));
            jTextFieldT20.setText(String.valueOf(T20));
            jTextFieldT22.setText(String.valueOf(T22));
            
            jButtonRealizarCambio.setEnabled(true);
            
            }


        }
    }//GEN-LAST:event_jTableProductosVendidosMouseClicked

    private void jButtonRealizarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarCambioActionPerformed
       // TODO add your handling code here:
        int cantT6 = (int) jSpinnerT6.getValue();
        int cantT8 = (int) jSpinnerT8.getValue();
        int cantT10 = (int) jSpinnerT10.getValue();
        int cantT12 = (int) jSpinnerT12.getValue();
        int cantT14 = (int) jSpinnerT14.getValue();
        int cantT16 = (int) jSpinnerT16.getValue();
        int cantT18 = (int) jSpinnerT18.getValue();
        int cantT20 = (int) jSpinnerT20.getValue();
        int cantT22 = (int) jSpinnerT22.getValue();
        int sumaP = cantT6 + cantT8 + cantT10 + cantT12 + cantT14 + cantT16 + cantT18 + cantT20 + cantT22;
        if (cantT6 < 0 || cantT8 < 0 || cantT10 < 0
                || cantT12 < 0 || cantT14 < 0 || cantT16 < 0
                || cantT18 < 0 || cantT20 < 0 || cantT22 < 0) {

            JOptionPane.showMessageDialog(this, "No debe ingresar valores negativos");
            jSpinnerT6.requestFocus();

        } else {

            if (sumaP == 0) {
                JOptionPane.showMessageDialog(this, "Debe devolver al menos 1 producto");
                jSpinnerT6.requestFocus();
            } else {
                int T6 = Integer.parseInt(jTextFieldT6.getText());
                int T8 = Integer.parseInt(jTextFieldT8.getText());
                int T10 = Integer.parseInt(jTextFieldT10.getText());
                int T12 = Integer.parseInt(jTextFieldT12.getText());
                int T14 = Integer.parseInt(jTextFieldT14.getText());
                int T16 = Integer.parseInt(jTextFieldT16.getText());
                int T18 = Integer.parseInt(jTextFieldT18.getText());
                int T20 = Integer.parseInt(jTextFieldT20.getText());
                int T22 = Integer.parseInt(jTextFieldT22.getText());

                if (cantT6 > T6 || cantT8 > T8 || cantT10 > T10
                        || cantT12 > T12 || cantT14 > T14 || cantT16 > T16
                        || cantT18 > T18 || cantT20 > T20 || cantT22 > T22) {

                    JOptionPane.showMessageDialog(this, "No puede devolver más de lo que se compro");
                    jSpinnerT6.requestFocus();

                } else {
                    actualizarDetalleVenta();
                    actualizarInventario();
                    actualizarVenta();
                    JOptionPane.showMessageDialog(this, "Devolución exitosa");
                    limpiarTabla();
                    reiniciarCant();
                    reiniciarDev();
                    jButtonRealizarCambio.setEnabled(false);

                }

            }

        }


    }//GEN-LAST:event_jButtonRealizarCambioActionPerformed
   public void reiniciarDev(){
        //Venta
        jTextFieldIdVenta.setText("");
        jTextFieldIdVenta.setEditable(true);
        jButtonBuscar.setEnabled(true);
        
        //cliente
        jTextFieldClienteNit.setText("");
        jTextFieldClienteNombre.setText("");
        jTextFieldClienteApellido.setText("");
        jTextFieldClienteTelefono.setText("");
        
        //producto
        
        jTextFieldProductoCodigo.setText("");
        jTextFieldProductoNombre.setText("");
        jTextFieldProductoPrecio.setText("");
        jTextFieldT6.setText("");
        jTextFieldT8.setText("");
        jTextFieldT10.setText("");
        jTextFieldT12.setText("");
        jTextFieldT14.setText("");
        jTextFieldT16.setText("");
        jTextFieldT18.setText("");
        jTextFieldT20.setText("");
        jTextFieldT22.setText("");

    }
    private void jTextFieldIdVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdVentaKeyTyped
                      char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldIdVentaKeyTyped

        
    public void soloNumeros(java.awt.event.KeyEvent evt, char v, int c){
    

        if (Character.isLetter(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo números");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        }
    
    
    }
    
    
    public void actualizarDetalleVenta(){
        int idVenta = Integer.parseInt(jTextFieldIdVenta.getText());
        String codigo = jTextFieldProductoCodigo.getText();
        ep = pDAO.buscar(codigo);
        int idProducto = ep.getIdProducto();
        
        int AT6 = Integer.parseInt(jTextFieldT6.getText());
        int AT8 = Integer.parseInt(jTextFieldT8.getText());
        int AT10 = Integer.parseInt(jTextFieldT10.getText());
        int AT12 = Integer.parseInt(jTextFieldT12.getText());
        int AT14 = Integer.parseInt(jTextFieldT14.getText());
        int AT16 = Integer.parseInt(jTextFieldT16.getText());
        int AT18 = Integer.parseInt(jTextFieldT18.getText());
        int AT20 = Integer.parseInt(jTextFieldT20.getText());
        int AT22 = Integer.parseInt(jTextFieldT22.getText());
        
        int CT6 = (int) jSpinnerT6.getValue();
        int CT8 = (int) jSpinnerT8.getValue();
        int CT10 = (int) jSpinnerT10.getValue();
        int CT12 = (int) jSpinnerT12.getValue();
        int CT14 = (int) jSpinnerT14.getValue();
        int CT16 = (int) jSpinnerT16.getValue();
        int CT18 = (int) jSpinnerT18.getValue();
        int CT20 = (int) jSpinnerT20.getValue();
        int CT22 = (int) jSpinnerT22.getValue();

        int NT6 = AT6 - CT6;
        int NT8 = AT8 - CT8;
        int NT10 = AT10 - CT10;
        int NT12 = AT12 - CT12;
        int NT14 = AT14 - CT14;
        int NT16 = AT16 - CT16;
        int NT18 = AT18 - CT18;
        int NT20 = AT20 - CT20;
        int NT22 = AT22 - CT22;
 
        double precio = Double.parseDouble(jTextFieldProductoPrecio.getText());
        
        double NSubtotal = (NT6+NT8+NT10+NT12+NT14+NT16+NT18+NT20+NT22)* precio;
        Object[] ob = new Object[12];
        
        ob[0] = NT6;
        ob[1] = NT8;
        ob[2] = NT10;
        ob[3] = NT12;
        ob[4] = NT14;
        ob[5] = NT16;
        ob[6] = NT18;
        ob[7] = NT20;
        ob[8] = NT22;
        ob[9] = NSubtotal;
        ob[10] = idVenta;
        ob[11] = idProducto;
        
        dvDAO.modificar(ob);
    
    }
    public void actualizarInventario(){
            String codigoP = jTextFieldProductoCodigo.getText();
            ep = pDAO.buscar(codigoP);
            int ActT6 = ep.getT6();
            int ActT8 = ep.getT8();
            int ActT10 = ep.getT10();
            int ActT12 = ep.getT12();
            int ActT14 = ep.getT14();
            int ActT16 = ep.getT16();
            int ActT18 = ep.getT18();
            int ActT20 = ep.getT20();
            int ActT22 = ep.getT22();
            
            int CT6 = (int) jSpinnerT6.getValue();
            int CT8 = (int) jSpinnerT8.getValue();
            int CT10 = (int) jSpinnerT10.getValue();
            int CT12 = (int) jSpinnerT12.getValue();
            int CT14 = (int) jSpinnerT14.getValue();
            int CT16 = (int) jSpinnerT16.getValue();
            int CT18 = (int) jSpinnerT18.getValue();
            int CT20 = (int) jSpinnerT20.getValue();
            int CT22 = (int) jSpinnerT22.getValue();
            
            int NT6 = ActT6 + CT6;
            int NT8 = ActT8 + CT8;
            int NT10 = ActT10 + CT10;
            int NT12 = ActT12 + CT12;
            int NT14 = ActT14 + CT14;
            int NT16 = ActT16 + CT16;
            int NT18 = ActT18 + CT18;
            int NT20 = ActT20 + CT20;
            int NT22 = ActT22 + CT22;
            
            double NStock = NT6+NT8+NT10+NT12+NT14+NT16+NT18+NT20+NT22;
            
            Object[] ob = new Object[11];
        
            ob[0]= NT6;
            ob[1]= NT8;
            ob[2]= NT10;
            ob[3]= NT12;
            ob[4]= NT14;
            ob[5]= NT16;
            ob[6]= NT18;
            ob[7]= NT20;
            ob[8]= NT22;
            ob[9]= NStock;
            ob[10]= codigoP;

            
            pDAO.reabastecer(ob);
    
    }
    public void actualizarVenta(){
        
        int idVenta = Integer.parseInt(jTextFieldIdVenta.getText());
        List<EntidadDetalleVenta> lista = dvDAO.listarPorIdVenta(idVenta);
        double total = 0;
        double subtotal;
        Object[] ob = new Object[2];

        for (int i = 0; i < lista.size(); i++) {

            subtotal = lista.get(i).getSubtotal();
            total = total + subtotal;

        }
        ob[0] = total;
        ob[1] = idVenta;

        vDAO.modificar(ob);
        
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRealizarCambio;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerT10;
    private javax.swing.JSpinner jSpinnerT12;
    private javax.swing.JSpinner jSpinnerT14;
    private javax.swing.JSpinner jSpinnerT16;
    private javax.swing.JSpinner jSpinnerT18;
    private javax.swing.JSpinner jSpinnerT20;
    private javax.swing.JSpinner jSpinnerT22;
    private javax.swing.JSpinner jSpinnerT6;
    private javax.swing.JSpinner jSpinnerT8;
    private javax.swing.JTable jTableProductosVendidos;
    private javax.swing.JTextField jTextFieldClienteApellido;
    private javax.swing.JTextField jTextFieldClienteNit;
    private javax.swing.JTextField jTextFieldClienteNombre;
    private javax.swing.JTextField jTextFieldClienteTelefono;
    private javax.swing.JTextField jTextFieldIdVenta;
    private javax.swing.JTextField jTextFieldProductoCodigo;
    private javax.swing.JTextField jTextFieldProductoNombre;
    private javax.swing.JTextField jTextFieldProductoPrecio;
    private javax.swing.JTextField jTextFieldT10;
    private javax.swing.JTextField jTextFieldT12;
    private javax.swing.JTextField jTextFieldT14;
    private javax.swing.JTextField jTextFieldT16;
    private javax.swing.JTextField jTextFieldT18;
    private javax.swing.JTextField jTextFieldT20;
    private javax.swing.JTextField jTextFieldT22;
    private javax.swing.JTextField jTextFieldT6;
    private javax.swing.JTextField jTextFieldT8;
    // End of variables declaration//GEN-END:variables
}
