
package Vistas.Admin.Ventas;

import DAOs.ClienteDAO;
import DAOs.DetalleVentaDAO;
import DAOs.ProductoDAO;
import DAOs.UsuarioDAO;
import DAOs.VentaDAO;
import Modelos.EntidadCliente;
import Modelos.EntidadDetalleVenta;
import Modelos.EntidadProducto;
import Modelos.EntidadUsuario;
import Modelos.EntidadVenta;

import Vistas.AutenticacionMenu.FormMenuAdmin;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AdminRealizarVentas extends javax.swing.JFrame {

    UsuarioDAO uDAO = new UsuarioDAO();
    EntidadUsuario eu = new EntidadUsuario();
    ClienteDAO cDAO = new ClienteDAO();
    EntidadCliente ec = new EntidadCliente();
    ProductoDAO pDAO = new ProductoDAO();
    EntidadProducto ep = new EntidadProducto();
    VentaDAO vDAO = new VentaDAO();
    EntidadVenta ev = new EntidadVenta();
    DetalleVentaDAO dvDAO = new DetalleVentaDAO();
    EntidadDetalleVenta edv = new EntidadDetalleVenta();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public AdminRealizarVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Realizar Venta");
        //generarPDF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jSpinner11 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNitCliente = new javax.swing.JTextField();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonAgregarBuscarCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTelefonoCliente = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNitVendedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNombreVendedor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        jTextFieldNombreProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPrecioProducto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonBuscarProducto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldT6 = new javax.swing.JTextField();
        jSpinnerT6 = new javax.swing.JSpinner();
        jTextFieldT8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerT8 = new javax.swing.JSpinner();
        jTextFieldT10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSpinnerT10 = new javax.swing.JSpinner();
        jTextFieldT12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSpinnerT12 = new javax.swing.JSpinner();
        jTextFieldT14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSpinnerT14 = new javax.swing.JSpinner();
        jTextFieldT16 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSpinnerT16 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldT18 = new javax.swing.JTextField();
        jSpinnerT18 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldT20 = new javax.swing.JTextField();
        jSpinnerT20 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldT22 = new javax.swing.JTextField();
        jSpinnerT22 = new javax.swing.JSpinner();
        jButtonAgregarProducto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrepararVenta = new javax.swing.JTable();
        jTextFieldTotalVenta = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBoxMetododePago = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jButtonFactura = new javax.swing.JButton();
        jButtonRealizarVenta = new javax.swing.JButton();
        jButtonNuevaVenta = new javax.swing.JButton();

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("T6");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("T6");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("T6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Ventas.png"))); // NOI18N
        jLabel1.setText("REALIZAR VENTA");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IDENTIFICACIÓN/NIT");

        jTextFieldNitCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNitClienteActionPerformed(evt);
            }
        });
        jTextFieldNitCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNitClienteKeyTyped(evt);
            }
        });

        jTextFieldNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreClienteActionPerformed(evt);
            }
        });
        jTextFieldNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreClienteKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");

        jTextFieldApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoClienteActionPerformed(evt);
            }
        });
        jTextFieldApellidoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoClienteKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("APELLIDO");

        jButtonAgregarBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAgregarBuscarCliente.setText("AGREGAR");
        jButtonAgregarBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarBuscarClienteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TELÉFONO");

        jTextFieldTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoClienteActionPerformed(evt);
            }
        });
        jTextFieldTelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoClienteKeyTyped(evt);
            }
        });

        jButtonBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarCliente.setText("BUSCAR");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOTA:Sí el cliente es una empresa en el campo apellido ingresar \"No aplica\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAgregarBuscarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNombreCliente)
                            .addComponent(jTextFieldApellidoCliente)
                            .addComponent(jTextFieldTelefonoCliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarBuscarCliente)
                    .addComponent(jButtonBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Vendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IDENTIFICACIÓN");

        jTextFieldNitVendedor.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOMBRE");

        jTextFieldNombreVendedor.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldNitVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNitVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CÓDIGO");

        jTextFieldCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoProductoActionPerformed(evt);
            }
        });
        jTextFieldCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoProductoKeyTyped(evt);
            }
        });

        jTextFieldNombreProducto.setEditable(false);
        jTextFieldNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreProductoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NOMBRE");

        jTextFieldPrecioProducto.setEditable(false);
        jTextFieldPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioProductoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRECIO");

        jButtonBuscarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarProducto.setText("BUSCAR");
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("T6");

        jTextFieldT6.setEditable(false);

        jTextFieldT8.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("T8");

        jTextFieldT10.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("T10");

        jTextFieldT12.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("T12");

        jTextFieldT14.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("T14");

        jTextFieldT16.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("T16");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("T18");

        jTextFieldT18.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("T20");

        jTextFieldT20.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("T22");

        jTextFieldT22.setEditable(false);

        jButtonAgregarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAgregarProducto.setText("AGREGAR");
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonAgregarProducto)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(16, 16, 16)
                                        .addComponent(jTextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldT8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerT8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldT6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerT6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldT12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerT12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldT14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerT14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jTextFieldT18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerT18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jTextFieldT20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerT20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(21, 21, 21)
                                .addComponent(jTextFieldPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerT10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerT16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldT22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerT22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProducto)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButtonAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preparación de venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTablePrepararVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRE", "T6", "T8", "T10", "T12", "T14", "T16", "T18", "T20", "T22", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePrepararVenta);
        if (jTablePrepararVenta.getColumnModel().getColumnCount() > 0) {
            jTablePrepararVenta.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTablePrepararVenta.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTablePrepararVenta.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(6).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(7).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(8).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(9).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(10).setPreferredWidth(30);
            jTablePrepararVenta.getColumnModel().getColumn(11).setPreferredWidth(100);
        }

        jTextFieldTotalVenta.setEditable(false);
        jTextFieldTotalVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalVentaActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TOTAL ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PAGO");

        jComboBoxMetododePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione metodo de pago", "Efectivo" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMetododePago, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBoxMetododePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButtonVolver.setBackground(new java.awt.Color(255, 153, 153));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVolver.setText("VOLVER");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonFactura.setBackground(new java.awt.Color(0, 153, 204));
        jButtonFactura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonFactura.setText("COMPROBANTE DE PAGO");
        jButtonFactura.setEnabled(false);
        jButtonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturaActionPerformed(evt);
            }
        });

        jButtonRealizarVenta.setBackground(new java.awt.Color(204, 255, 204));
        jButtonRealizarVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRealizarVenta.setText("REALIZAR VENTA");
        jButtonRealizarVenta.setEnabled(false);
        jButtonRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarVentaActionPerformed(evt);
            }
        });

        jButtonNuevaVenta.setBackground(new java.awt.Color(255, 255, 153));
        jButtonNuevaVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNuevaVenta.setText("NUEVA VENTA");
        jButtonNuevaVenta.setEnabled(false);
        jButtonNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRealizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRealizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalVentaActionPerformed

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        // TODO add your handling code here:
        buscarProducto();
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    public void buscarProducto(){
            String codigo = jTextFieldCodigoProducto.getText();
        
        if(jTextFieldCodigoProducto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el código en la caja de texto");
            jTextFieldCodigoProducto.requestFocus();
        }else{
            nuevaConsultaProducto();
            ep = pDAO.buscarDisponible(codigo);
            if (ep.getCodigo()!= null ){
                
                if(ep.getStock()== 0){
                        
                    JOptionPane.showMessageDialog(this, "No hay existencias de este producto");
                
                }else{
                jTextFieldNombreProducto.setText(ep.getNombre());
                jTextFieldPrecioProducto.setText(String.valueOf(ep.getPrecioVenta()));
                jTextFieldT6.setText(String.valueOf(ep.getT6()));
                jTextFieldT8.setText(String.valueOf(ep.getT8()));
                jTextFieldT10.setText(String.valueOf(ep.getT10()));
                jTextFieldT12.setText(String.valueOf(ep.getT12()));
                jTextFieldT14.setText(String.valueOf(ep.getT14()));
                jTextFieldT16.setText(String.valueOf(ep.getT16()));
                jTextFieldT18.setText(String.valueOf(ep.getT18()));
                jTextFieldT20.setText(String.valueOf(ep.getT20()));
                jTextFieldT22.setText(String.valueOf(ep.getT22()));
                
                jButtonAgregarProducto.setEnabled(true);

                }

  
            }else{
                 JOptionPane.showMessageDialog(this,"El código de este producto no está registrado o el producto no esta disponible");
                 jTextFieldCodigoProducto.requestFocus();
             }
        } 
    }

    public void nuevaConsultaProducto() {

        jTextFieldNombreProducto.setText("");
        jTextFieldPrecioProducto.setText("");
        
        jTextFieldT6.setText("");
        jTextFieldT8.setText("");
        jTextFieldT10.setText("");
        jTextFieldT12.setText("");
        jTextFieldT14.setText("");
        jTextFieldT16.setText("");
        jTextFieldT18.setText("");
        jTextFieldT20.setText("");
        jTextFieldT22.setText("");

        jSpinnerT6.setValue(0);
        jSpinnerT8.setValue(0);
        jSpinnerT10.setValue(0);
        jSpinnerT12.setValue(0);
        jSpinnerT14.setValue(0);
        jSpinnerT16.setValue(0);
        jSpinnerT18.setValue(0);
        jSpinnerT20.setValue(0);
        jSpinnerT22.setValue(0);
    }
    
    private void jTextFieldPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioProductoActionPerformed

    }//GEN-LAST:event_jTextFieldPrecioProductoActionPerformed

    private void jTextFieldNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreProductoActionPerformed
  
    }//GEN-LAST:event_jTextFieldNombreProductoActionPerformed

    private void jTextFieldCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProductoActionPerformed
     
    }//GEN-LAST:event_jTextFieldCodigoProductoActionPerformed

    private void jTextFieldTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoClienteActionPerformed

    }//GEN-LAST:event_jTextFieldTelefonoClienteActionPerformed

    private void jButtonAgregarBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarBuscarClienteActionPerformed

     
        
        if(jTextFieldNitCliente.getText().equals("")|| jTextFieldNombreCliente.getText().equals("")
                ||jTextFieldApellidoCliente.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar los datos del cliente");
            jTextFieldNitCliente.requestFocus();
        }else{
              String nit = jTextFieldNitCliente.getText();
            ec = cDAO.buscar(nit);
            if (ec.getNit() != null ){
                  JOptionPane.showMessageDialog(this,"El nit de cliente que ingreso ya está registrado");
                  jTextFieldNombreCliente.setText("");
                  jTextFieldApellidoCliente.setText("");
                  jTextFieldTelefonoCliente.setText("");

            }else{
        agregarCliente();

             }
        } 

    }//GEN-LAST:event_jButtonAgregarBuscarClienteActionPerformed

    public void agregarCliente(){
        
        if(jTextFieldTelefonoCliente.getText().equals("")){
        String nit = jTextFieldNitCliente.getText();
        String nombre = jTextFieldNombreCliente.getText();
        String apellido = jTextFieldApellidoCliente.getText();
        String telefono = jTextFieldTelefonoCliente.getText();
      
        
        Object[] ob = new Object[4];
        
        ob[0]= nit;
        ob[1]= nombre;
        ob[2]= apellido;
        ob[3]= telefono;

        cDAO.agregar(ob);
                JOptionPane.showMessageDialog(this, "Cliente agregado");
    
        }else{
            
            String telefono2 = jTextFieldTelefonoCliente.getText();

            long telValidar = Long.parseLong(telefono2);
            long numMinTel = Long.parseLong("1000000");
            long numMaxTel = Long.parseLong("9999999");
            long numMinCel = Long.parseLong("3000000000");
            long numMaxCel = Long.parseLong("3999999999");

            if (telValidar < 0 || telValidar > 0 && telValidar < numMinTel
                    || telValidar > numMaxTel && telValidar < numMinCel
                    || telValidar > numMaxCel) {
                JOptionPane.showMessageDialog(this, "El número de teléfono opcional no es admisible\nEjemplo:\n"
                        + "Celular -> 31412178##\n"
                        + "Teléfono local -> 56278##");
                jTextFieldTelefonoCliente.requestFocus();

            }
            else{
                    String nit = jTextFieldNitCliente.getText();
        String nombre = jTextFieldNombreCliente.getText();
        String apellido = jTextFieldApellidoCliente.getText();
        String telefono = jTextFieldTelefonoCliente.getText();
      
        
        Object[] ob = new Object[4];
        
        ob[0]= nit;
        ob[1]= nombre;
        ob[2]= apellido;
        ob[3]= telefono;

        cDAO.agregar(ob);
                JOptionPane.showMessageDialog(this, "Cliente agregado");
            
            
            }
        
        
        
        }
    }
    
    private void jTextFieldApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoClienteActionPerformed

    private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreClienteActionPerformed

    private void jTextFieldNitClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNitClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNitClienteActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        FormMenuAdmin abrir = new FormMenuAdmin();
        abrir.setVisible(true);
        abrir.jTextFieldIdUsuario.setText(jTextFieldNitVendedor.getText());
        abrir.jTextFieldNombre.setText(jTextFieldNombreVendedor.getText());
        abrir.jTextFieldRol.setText("Administrador");
        this.dispose();
        
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        buscarCliente();
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed

        if (jTextFieldNitCliente.getText().equals("") || jTextFieldNombreCliente.getText().equals("")
                || jTextFieldApellidoCliente.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Faltan datos del cliente");
        } else {

            String codigoActual = jTextFieldCodigoProducto.getText();
            int r = 0;

            for (int i = 0; i < jTablePrepararVenta.getRowCount(); i++) {

                String productoPreparado = jTablePrepararVenta.getValueAt(i, 0).toString();
                if (codigoActual.equals(productoPreparado)) {

                    r = 1;
                    break;
                }

            }
            if (r == 1) {
                JOptionPane.showMessageDialog(this, "No puede volver a ingresar este producto");
                nuevaConsultaProducto();
                jTextFieldCodigoProducto.requestFocus();
            } else {
                if (jTextFieldCodigoProducto.getText().equals("") || jTextFieldT6.getText().equals("")) {

                    JOptionPane.showMessageDialog(this, "Debe ingresar el producto y buscar sus disponibilidades");
                    jTextFieldCodigoProducto.requestFocus();

                } else {
                    int cantT6 = (int) jSpinnerT6.getValue();
                    int cantT8 = (int) jSpinnerT8.getValue();
                    int cantT10 = (int) jSpinnerT10.getValue();
                    int cantT12 = (int) jSpinnerT12.getValue();
                    int cantT14 = (int) jSpinnerT14.getValue();
                    int cantT16 = (int) jSpinnerT16.getValue();
                    int cantT18 = (int) jSpinnerT18.getValue();
                    int cantT20 = (int) jSpinnerT20.getValue();
                    int cantT22 = (int) jSpinnerT22.getValue();
                    int sumaP = cantT6 + cantT8 + cantT10 + cantT12 + cantT14 + cantT16 + cantT18 + cantT20 + cantT22;
                    if (cantT6 < 0 || cantT8 < 0 || cantT10 < 0
                            || cantT12 < 0 || cantT14 < 0 || cantT16 < 0
                            || cantT18 < 0 || cantT20 < 0 || cantT22 < 0) {

                        JOptionPane.showMessageDialog(this, "No debe ingresar valores negativos");
                        jSpinnerT6.requestFocus();

                    } else {

                        if (sumaP <= 0) {

                            JOptionPane.showMessageDialog(this, "Debe ingresar al menos 1 producto");
                            jSpinnerT6.requestFocus();
                        } else {
                            int T6 = Integer.parseInt(jTextFieldT6.getText());
                            int T8 = Integer.parseInt(jTextFieldT8.getText());
                            int T10 = Integer.parseInt(jTextFieldT10.getText());
                            int T12 = Integer.parseInt(jTextFieldT12.getText());
                            int T14 = Integer.parseInt(jTextFieldT14.getText());
                            int T16 = Integer.parseInt(jTextFieldT16.getText());
                            int T18 = Integer.parseInt(jTextFieldT18.getText());
                            int T20 = Integer.parseInt(jTextFieldT20.getText());
                            int T22 = Integer.parseInt(jTextFieldT22.getText());

                            if (cantT6 > T6 || cantT8 > T8 || cantT10 > T10
                                    || cantT12 > T12 || cantT14 > T14 || cantT16 > T16
                                    || cantT18 > T18 || cantT20 > T20 || cantT22 > T22) {

                                JOptionPane.showMessageDialog(this, "La compra no puede exceder la existencias");
                                jSpinnerT6.requestFocus();

                            } else {
                                agregarProducto();
                                jButtonRealizarVenta.setEnabled(true);
                                jTextFieldNitCliente.setEditable(false);
                                jTextFieldNombreCliente.setEditable(false);
                                jTextFieldApellidoCliente.setEditable(false);
                                jTextFieldTelefonoCliente.setEditable(false);
                                jButtonAgregarBuscarCliente.setEnabled(false);
                                jButtonBuscarCliente.setEnabled(false);
                                jButtonAgregarProducto.setEnabled(false);
     
                                nuevaConsultaProducto();
                            }

                        }

                    }

                }

            }
        }
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jButtonRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarVentaActionPerformed
        // TODO add your handling code here:
        
        if(jTextFieldNitCliente.getText().equals("")||jTextFieldNombreCliente.getText().equals("")
                ||jTextFieldApellidoCliente.getText().equals("")){
        
            
           JOptionPane.showMessageDialog(this, "Faltan datos del cliente");
        }else{
        
        agregarVenta();
        agregarDetalleVenta();
        actualizarInventario();
        JOptionPane.showMessageDialog(this, "Venta Realizada");
        congelarVenta();
        //limpiarTabla();
        jButtonRealizarVenta.setEnabled(false);
        jButtonFactura.setEnabled(true);
        jButtonNuevaVenta.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonRealizarVentaActionPerformed

    public void congelarVenta(){
    //Cliente
    jTextFieldNitCliente.setEditable(false);
    jTextFieldNombreCliente.setEditable(false);
    jTextFieldApellidoCliente.setEditable(false);
    jTextFieldTelefonoCliente.setEditable(false);
    jButtonAgregarBuscarCliente.setEnabled(false);
    jButtonBuscarCliente.setEnabled(false);
    
    //Producto
    jTextFieldCodigoProducto.setEditable(false);
    jButtonBuscarProducto.setEnabled(false);
    jSpinnerT6.setEnabled(false);
    jSpinnerT8.setEnabled(false);
    jSpinnerT10.setEnabled(false);
    jSpinnerT12.setEnabled(false);
    jSpinnerT14.setEnabled(false);
    jSpinnerT16.setEnabled(false);
    jSpinnerT18.setEnabled(false);
    jSpinnerT20.setEnabled(false);
    jSpinnerT22.setEnabled(false);
    jButtonAgregarProducto.setEnabled(false);
    
    //Tabla
    
    jTablePrepararVenta.setEnabled(false);
    
    
    jComboBoxMetododePago.setEnabled(false);
    
    }
    
    public void soloLetras(java.awt.event.KeyEvent evt, char v, int c){
        
        if (Character.isLowerCase(v)){
        
           evt.setKeyChar(Character.toUpperCase(v));
            
        }      
        if (Character.isDigit(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo letras");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        } 
        
    }
       public void soloLetrasConEspacio(java.awt.event.KeyEvent evt, char v, int c){
        
        if (Character.isLowerCase(v)){
        
           evt.setKeyChar(Character.toUpperCase(v));
            
        }      
        if (Character.isDigit(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo letras");
            
        }

        
       if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        } 
        
    }
   public void soloNumeros(java.awt.event.KeyEvent evt, char v, int c){
    

        if (Character.isLetter(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo números");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        }
    
    
    }
       public void SoloLetrasNumeros(java.awt.event.KeyEvent evt, char v, int c){
    
        if (Character.isLowerCase(v)) {

            evt.setKeyChar(Character.toUpperCase(v));

        }

        if (Character.isSpaceChar(v)) {

            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");

        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255) {
            System.out.println(c);
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");

        }
    
    }
    
    
    private void jTextFieldNitClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNitClienteKeyTyped
        // TODO add your handling code here:
                  char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldNitClienteKeyTyped

    private void jTextFieldNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteKeyTyped
                  char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloLetrasConEspacio(evt, v, c);
    }//GEN-LAST:event_jTextFieldNombreClienteKeyTyped

    private void jTextFieldApellidoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoClienteKeyTyped
                 char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloLetrasConEspacio(evt, v, c);
    }//GEN-LAST:event_jTextFieldApellidoClienteKeyTyped

    private void jTextFieldTelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoClienteKeyTyped
                  char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldTelefonoClienteKeyTyped

    private void jTextFieldCodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProductoKeyTyped
                char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        SoloLetrasNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldCodigoProductoKeyTyped

    private void jButtonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturaActionPerformed
        generarPDF();
        jButtonFactura.setEnabled(false);
    }//GEN-LAST:event_jButtonFacturaActionPerformed

    private void jButtonNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaVentaActionPerformed
        AdminRealizarVentas abrir = new AdminRealizarVentas();
        abrir.setVisible(true);
        abrir.jTextFieldNitVendedor.setText(jTextFieldNitVendedor.getText());
        abrir.jTextFieldNombreVendedor.setText(jTextFieldNombreVendedor.getText());
        this.dispose();
    }//GEN-LAST:event_jButtonNuevaVentaActionPerformed
public void generarPDF(){
    
int idVenta = Integer.parseInt(vDAO.obtenerIdVenta());
    try {
        LocalDate fechaD = LocalDate.now();
        FileOutputStream archivo; 
     
        File documentoRuta = new File("C:/EyesJeansPDF/factura_" + idVenta +".pdf");

        archivo = new FileOutputStream(documentoRuta);
        
        Document documento = new Document();
        PdfWriter.getInstance(documento, archivo);
        

        documento.open();
        
        Image imagen = Image.getInstance("src/Img/Logo.jpg");
        
        Paragraph fecha = new Paragraph();
        Font fuenteLetra = new Font(Font.FontFamily.TIMES_ROMAN,12,Font.BOLD,BaseColor.BLUE);
        Font letrita = new Font(Font.FontFamily.TIMES_ROMAN,5,Font.NORMAL,BaseColor.BLUE);
        Font bold= new Font(Font.FontFamily.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLACK);
        
        fecha.add(Chunk.NEWLINE);
        fecha.add("Fecha: " + fechaD + "\n\n");
        
        PdfPTable partUp = new PdfPTable(4);
        partUp.setWidthPercentage(100);
        partUp.getDefaultCell().setBorder(0);
        
        float[] ColumnaPartUp = new float[]{20f,30f,70f,40f};
        
        partUp.setWidths(ColumnaPartUp);
        partUp.setHorizontalAlignment(Element.ALIGN_CENTER);
        
        partUp.addCell(imagen);
        String nitEmpresa = "N.I.T 39.787.549 - 0 Régimen Simplificado";
        String nombreEmpresa = "Eyes Jeans";
        String telefonosEmpresa = "313 215 17 67 ";
        String telefonoPedido = "Pedidos: 320 311 41 70";
        String numVenta = String.valueOf(idVenta);
        String direccionEmpresa = "Cr 11 # 10-79 CC Volga 8 - Puesto 24";
        
        partUp.addCell("");
        partUp.addCell(nitEmpresa + "\n" + nombreEmpresa + "\n" + "Telefono: " + telefonosEmpresa + "\n" + telefonoPedido
                       + "\n" + direccionEmpresa + "\n\n" + "ID Venta : " + numVenta);
        
        partUp.addCell(fecha);
        
        documento.add(partUp);
        //Inicio datos del cliente 
        Paragraph infoCliente = new Paragraph();
        infoCliente.add(Chunk.NEWLINE);
        infoCliente.setFont(bold);
        infoCliente.add("Datos del cliente\n\n");
        documento.add(infoCliente);

        PdfPTable datosCliente = new PdfPTable(4);
        datosCliente.setWidthPercentage(100);
        datosCliente.getDefaultCell().setBorder(0);

        float[] ColumnaCliente = new float[]{40f, 50f, 50f, 40f};

        datosCliente.setWidths(ColumnaCliente);
        datosCliente.setHorizontalAlignment(Element.ALIGN_CENTER);
        PdfPCell idClienteTitle = new PdfPCell(new Phrase("Identificación",fuenteLetra));
        PdfPCell nombreClienteTitle = new PdfPCell(new Phrase("Nombre",fuenteLetra));
        PdfPCell apellidoClienteTitle = new PdfPCell(new Phrase("Apellido",fuenteLetra));
        PdfPCell telefonoClienteTitle = new PdfPCell(new Phrase("Teléfono",fuenteLetra));
        
        idClienteTitle.setBorder(1);
        nombreClienteTitle.setBorder(1);
        apellidoClienteTitle.setBorder(1);
        telefonoClienteTitle.setBorder(1);
        
        datosCliente.addCell(idClienteTitle);
        datosCliente.addCell(nombreClienteTitle);
        datosCliente.addCell(apellidoClienteTitle);
        datosCliente.addCell(telefonoClienteTitle);

        datosCliente.addCell(jTextFieldNitCliente.getText());
        datosCliente.addCell(jTextFieldNombreCliente.getText());
        datosCliente.addCell(jTextFieldApellidoCliente.getText());
        datosCliente.addCell(jTextFieldTelefonoCliente.getText());
   
        documento.add(datosCliente);
        // Fin datos cliente
        //Datos Vendedor
        Paragraph infoVendedor = new Paragraph();
        infoVendedor.add(Chunk.NEWLINE);
        infoVendedor.setFont(bold);
        infoVendedor.add("Datos del vendedor\n\n");
        documento.add(infoVendedor);

        PdfPTable datosVendedor = new PdfPTable(2);
        datosVendedor.setWidthPercentage(100);
        datosVendedor.getDefaultCell().setBorder(0);

        float[] ColumnaVendedor = new float[]{50f, 50f};

        datosVendedor.setWidths(ColumnaVendedor);
        datosVendedor.setHorizontalAlignment(Element.ALIGN_CENTER);
        PdfPCell idVendedorTitle = new PdfPCell(new Phrase("Identificación",fuenteLetra));
        PdfPCell nombreVendedorTitle = new PdfPCell(new Phrase("Nombre",fuenteLetra));

        
        idVendedorTitle.setBorder(1);
        nombreVendedorTitle.setBorder(1);
    
        datosVendedor.addCell(idVendedorTitle);
        datosVendedor.addCell(nombreVendedorTitle);
        datosVendedor.addCell(jTextFieldNitVendedor.getText());
        datosVendedor.addCell(jTextFieldNombreVendedor.getText());

        documento.add(datosVendedor);
        
        //fin datos vendedor

        //inicio detalle venta 
        Paragraph infoDetalleVenta = new Paragraph();
        infoDetalleVenta.add(Chunk.NEWLINE);
        infoDetalleVenta.setFont(bold);
        infoDetalleVenta.add("\n\n\nDetalle de venta\n\n");
        infoDetalleVenta.setAlignment(Element.ALIGN_CENTER);
        documento.add(infoDetalleVenta);
        
        PdfPTable datosDetalleVenta = new PdfPTable(12);
        datosDetalleVenta.setWidthPercentage(100);
        datosDetalleVenta.getDefaultCell().setBorder(0);

        float[] ColumnaDetalleVenta = new float[]{15f,15f,5f,5f,5f,5f,5f,5f,5f,5f,5f,20f};
        datosDetalleVenta.setWidths(ColumnaDetalleVenta);
        datosDetalleVenta.setHorizontalAlignment(Element.ALIGN_CENTER);
        PdfPCell productoCodigoTitle = new PdfPCell(new Phrase("Código",fuenteLetra));
        PdfPCell productoNombreTitle = new PdfPCell(new Phrase("Nombre",fuenteLetra));
        PdfPCell productoT6Title = new PdfPCell(new Phrase("T6",fuenteLetra));
        PdfPCell productoT8Title = new PdfPCell(new Phrase("T8",fuenteLetra));
        PdfPCell productoT10Title = new PdfPCell(new Phrase("T10",fuenteLetra));
        PdfPCell productoT12Title = new PdfPCell(new Phrase("T12",fuenteLetra));
        PdfPCell productoT14Title = new PdfPCell(new Phrase("T14",fuenteLetra));
        PdfPCell productoT16Title = new PdfPCell(new Phrase("T16",fuenteLetra));
        PdfPCell productoT18Title = new PdfPCell(new Phrase("T18",fuenteLetra));
        PdfPCell productoT20Title = new PdfPCell(new Phrase("T20",fuenteLetra));
        PdfPCell productoT22Title = new PdfPCell(new Phrase("T22",fuenteLetra));
        PdfPCell productoSubtotalTitle = new PdfPCell(new Phrase("Subtotal",fuenteLetra));
        
        productoCodigoTitle.setBorder(1);
        productoNombreTitle.setBorder(1);
        productoT6Title.setBorder(1);
        productoT8Title.setBorder(1);
        productoT10Title.setBorder(1);
        productoT12Title.setBorder(1);
        productoT14Title.setBorder(1);
        productoT16Title.setBorder(1);
        productoT18Title.setBorder(1);
        productoT20Title.setBorder(1);
        productoT22Title.setBorder(1);
        productoSubtotalTitle.setBorder(1);

        datosDetalleVenta.addCell(productoCodigoTitle);
        datosDetalleVenta.addCell(productoNombreTitle);
        datosDetalleVenta.addCell(productoT6Title);
        datosDetalleVenta.addCell(productoT8Title);
        datosDetalleVenta.addCell(productoT10Title);
        datosDetalleVenta.addCell(productoT12Title);
        datosDetalleVenta.addCell(productoT14Title);
        datosDetalleVenta.addCell(productoT16Title);
        datosDetalleVenta.addCell(productoT18Title);
        datosDetalleVenta.addCell(productoT20Title);
        datosDetalleVenta.addCell(productoT22Title);
        datosDetalleVenta.addCell(productoSubtotalTitle);
        
        String codigoP,nombreP;
        int T6P,T8P,T10P,T12P,T14P,T16P,T18P,T20P,T22P;
        double subtotal;
        for (int i = 0; i < jTablePrepararVenta.getRowCount(); i++) {
            codigoP = jTablePrepararVenta.getValueAt(i, 0).toString();
            nombreP = jTablePrepararVenta.getValueAt(i, 1).toString();
            T6P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 2).toString());
            T8P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 3).toString());
            T10P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 4).toString());
            T12P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 5).toString());
            T14P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 6).toString());
            T16P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 7).toString());
            T18P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 8).toString());
            T20P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 9).toString());
            T22P = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 10).toString());
            subtotal = Double.parseDouble((jTablePrepararVenta.getValueAt(i, 11).toString()));
            
            datosDetalleVenta.addCell(codigoP);
            datosDetalleVenta.addCell(nombreP); 
            if (T6P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T6P));
            }
            if (T8P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T8P));
            }
            if (T10P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T10P));
            }
            if (T12P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T12P));
            }
            if (T14P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T14P));
            }
            if (T16P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T16P));
            }
            if (T18P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T18P));
            }
            if (T20P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T20P));
            }
            if (T22P == 0) {
                datosDetalleVenta.addCell("-");
            } else {
                datosDetalleVenta.addCell(String.valueOf(T22P));
            }
            
            datosDetalleVenta.addCell(String.valueOf(subtotal));

        }
        
        documento.add(datosDetalleVenta);

        //fin detalle venta
        
        //inicio pie de pagina
        
        Paragraph pieDePagina = new Paragraph();
        pieDePagina.add(Chunk.NEWLINE);
        pieDePagina.add("\n\nMétodo de pago : EFECTIVO\n");
        pieDePagina.add("TOTAL A PAGAR : " + jTextFieldTotalVenta.getText() + " COP" +"\n\n");
        pieDePagina.setAlignment(Element.ALIGN_RIGHT);
        documento.add(pieDePagina);
        
        
        Paragraph firma = new Paragraph();
        firma.add(Chunk.NEWLINE);
        firma.add("\n\n-------------------------------\n");
        firma.add("FIRMA AUTORIZADA");
        firma.setAlignment(Element.ALIGN_CENTER);
        documento.add(firma);
        
        Paragraph gracias = new Paragraph();
        gracias.add(Chunk.NEWLINE);
        gracias.add("\n\n\nGRACIAS POR SU COMPRA :D");
        gracias.setAlignment(Element.ALIGN_CENTER);
        documento.add(gracias);
        
        Paragraph leyTerm = new Paragraph();
        leyTerm.setFont(letrita);
        leyTerm.add(Chunk.NEWLINE);
        leyTerm.add("\n\n\n");
        String ley = "ESTA FACTURA DE VENTA PARA TODOS SUS EFECTOS LEGALES ES UN ";
        String ley2 = "TITULO VALOR SEGÚN LEY 1231 DEJULIO 17 DE 2008";
        leyTerm.add(ley + ley2);
        leyTerm.setAlignment(Element.ALIGN_CENTER);
        documento.add(leyTerm);
 
        //final pie de pagina
        
        documento.close();
        archivo.close();
        Desktop.getDesktop().open(documentoRuta);
        
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
        System.out.println(e);
    }
}
    
        public void limpiarTabla(){
    
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    public void actualizarInventario(){
        
             for (int i = 0; i < jTablePrepararVenta.getRowCount(); i++) {
            
            String codigoProducto = jTablePrepararVenta.getValueAt(i, 0).toString();
            ep = pDAO.buscar(codigoProducto);
            int ActT6 = ep.getT6();
            int ActT8 = ep.getT8();
            int ActT10 = ep.getT10();
            int ActT12 = ep.getT12();
            int ActT14 = ep.getT14();
            int ActT16 = ep.getT16();
            int ActT18 = ep.getT18();
            int ActT20 = ep.getT20();
            int ActT22 = ep.getT22();
            
            int CantT6 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 2).toString());
            int CantT8 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 3).toString());
            int CantT10 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 4).toString());
            int CantT12 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 5).toString());
            int CantT14 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 6).toString());
            int CantT16 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 7).toString());
            int CantT18 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 8).toString());
            int CantT20 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 9).toString());
            int CantT22 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 10).toString());
            
            int NT6 = ActT6 - CantT6;
            int NT8 = ActT8 - CantT8;
            int NT10 = ActT10 - CantT10;
            int NT12 = ActT12 - CantT12;
            int NT14 = ActT14 - CantT14;
            int NT16 = ActT16 - CantT16;
            int NT18 = ActT18 - CantT18;
            int NT20 = ActT20 - CantT20;
            int NT22 = ActT22 - CantT22;
            
            int NStock = NT6 + NT8 + NT10 + NT12 + NT14 + NT16 + NT18 + NT20 + NT22; 
            
            Object[] ob = new Object[11];
        
            ob[0]= NT6;
            ob[1]= NT8;
            ob[2]= NT10;
            ob[3]= NT12;
            ob[4]= NT14;
            ob[5]= NT16;
            ob[6]= NT18;
            ob[7]= NT20;
            ob[8]= NT22;
            ob[9]= NStock;
            ob[10]= codigoProducto;

            
            pDAO.reabastecer(ob);

        }
        
    
    }
    public void agregarVenta(){
        LocalDate fechaD = LocalDate.now();
        int metodoPago=0;
        
        String fecha = ""+fechaD;
        double total = Double.parseDouble(jTextFieldTotalVenta.getText());
        int idVendedor=0;
        String nitVendedor = jTextFieldNitVendedor.getText();
        eu = uDAO.buscar(nitVendedor);
        idVendedor = eu.getIdUsuario();
        metodoPago = 1;
        int idCliente=0;
        String nitCliente = jTextFieldNitCliente.getText();
        ec = cDAO.buscar(nitCliente);
        idCliente = ec.getIdCliente();
                
     
        Object[] ob = new Object[5];
        
        ob[0]= fecha;
        ob[1]= total;
        ob[2]= idVendedor;
        ob[3]= metodoPago;
        ob[4]= idCliente;
        
        vDAO.agregar(ob);
              
    }
    
    public void agregarDetalleVenta(){
    
        int idVenta = Integer.parseInt(vDAO.obtenerIdVenta());
        for (int i = 0; i < jTablePrepararVenta.getRowCount(); i++) {
            
            String codigoProducto = jTablePrepararVenta.getValueAt(i, 0).toString();
            ep = pDAO.buscar(codigoProducto);
            int idProducto = ep.getIdProducto();
            int CantT6 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 2).toString());
            int CantT8 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 3).toString());
            int CantT10 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 4).toString());
            int CantT12 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 5).toString());
            int CantT14 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 6).toString());
            int CantT16 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 7).toString());
            int CantT18 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 8).toString());
            int CantT20 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 9).toString());
            int CantT22 = Integer.parseInt(jTablePrepararVenta.getValueAt(i, 10).toString());
            double subtotal = Double.parseDouble(jTablePrepararVenta.getValueAt(i, 11).toString());
            
            Object[] ob = new Object[12];
        
            ob[0]= idVenta;
            ob[1]= idProducto;
            ob[2]= CantT6;
            ob[3]= CantT8;
            ob[4]= CantT10;
            ob[5]= CantT12;
            ob[6]= CantT14;
            ob[7]= CantT16;
            ob[8]= CantT18;
            ob[9]= CantT20;
            ob[10]= CantT22;
            ob[11]= subtotal;
            
            dvDAO.agregar(ob);

        }
    
    }
    public void agregarProducto(){
    
        modelo = (DefaultTableModel)jTablePrepararVenta.getModel();
        String codigoProducto = ep.getCodigo();
        String nombreProducto = jTextFieldNombreProducto.getText();
        int cantT6 = (int) jSpinnerT6.getValue();
        int cantT8 = (int) jSpinnerT8.getValue();
        int cantT10 = (int) jSpinnerT10.getValue();
        int cantT12 = (int) jSpinnerT12.getValue();
        int cantT14 = (int) jSpinnerT14.getValue();
        int cantT16 = (int) jSpinnerT16.getValue();
        int cantT18 = (int) jSpinnerT18.getValue();
        int cantT20 = (int) jSpinnerT20.getValue();
        int cantT22 = (int) jSpinnerT22.getValue();
        int precio = Integer.parseInt(jTextFieldPrecioProducto.getText());
        double subtotal =(double)(cantT6 + cantT8 + cantT10 + cantT12 + cantT14 + cantT16 + cantT18 + cantT20 + cantT22)*precio;
        
        int stock = (cantT6 + cantT8 + cantT10 + cantT12 + cantT14 + cantT16 + cantT18 + cantT20 + cantT22);
        ArrayList listaProducto = new ArrayList ();
        
  
            listaProducto.add(codigoProducto);
            listaProducto.add(nombreProducto);
            listaProducto.add(cantT6);
            listaProducto.add(cantT8);
            listaProducto.add(cantT10);
            listaProducto.add(cantT12);
            listaProducto.add(cantT14);
            listaProducto.add(cantT16);
            listaProducto.add(cantT18);
            listaProducto.add(cantT20);
            listaProducto.add(cantT22);
            listaProducto.add(subtotal);
            
            Object[] ob = new Object[12];
            
            ob[0] = listaProducto.get(0);
            ob[1] = listaProducto.get(1);
            ob[2] = listaProducto.get(2);
            ob[3] = listaProducto.get(3);
            ob[4] = listaProducto.get(4);
            ob[5] = listaProducto.get(5);
            ob[6] = listaProducto.get(6);
            ob[7] = listaProducto.get(7);
            ob[8] = listaProducto.get(8);
            ob[9] = listaProducto.get(9);
            ob[10] = listaProducto.get(10);
            ob[11] = listaProducto.get(11);
            
            modelo.addRow(ob);
            
            jTablePrepararVenta.setModel(modelo);
            generarTotal();
         
        
    }
    
    public void generarTotal(){
    
        double total = 0;
        double subtotal;
        for (int i = 0; i < jTablePrepararVenta.getRowCount(); i++) {
            subtotal = Double.parseDouble((jTablePrepararVenta.getValueAt(i, 11).toString()));
            total = total + subtotal;
            
        }
        
        jTextFieldTotalVenta.setText(String.valueOf(total));
    }
    
    public void buscarCliente(){
            String nit = jTextFieldNitCliente.getText();
        
        if(jTextFieldNitCliente.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el nit en la caja de texto");
            jTextFieldNitCliente.requestFocus();
        }else{
            
            ec = cDAO.buscar(nit);
            if (ec.getNit() != null ){
                jTextFieldNombreCliente.setText(ec.getNombre());
                jTextFieldApellidoCliente.setText(ec.getApellido());
                jTextFieldTelefonoCliente.setText(ec.getTelefono());

            }else{
                 JOptionPane.showMessageDialog(this,"El nit que ingreso no está registrado");
                 jTextFieldNitCliente.requestFocus();
             }
        } 
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarBuscarCliente;
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JButton jButtonFactura;
    private javax.swing.JButton jButtonNuevaVenta;
    private javax.swing.JButton jButtonRealizarVenta;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxMetododePago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JSpinner jSpinnerT10;
    private javax.swing.JSpinner jSpinnerT12;
    private javax.swing.JSpinner jSpinnerT14;
    private javax.swing.JSpinner jSpinnerT16;
    private javax.swing.JSpinner jSpinnerT18;
    private javax.swing.JSpinner jSpinnerT20;
    private javax.swing.JSpinner jSpinnerT22;
    private javax.swing.JSpinner jSpinnerT6;
    private javax.swing.JSpinner jSpinnerT8;
    private javax.swing.JTable jTablePrepararVenta;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldApellidoCliente;
    private javax.swing.JTextField jTextFieldCodigoProducto;
    private javax.swing.JTextField jTextFieldNitCliente;
    public javax.swing.JTextField jTextFieldNitVendedor;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNombreProducto;
    public javax.swing.JTextField jTextFieldNombreVendedor;
    private javax.swing.JTextField jTextFieldPrecioProducto;
    private javax.swing.JTextField jTextFieldT10;
    private javax.swing.JTextField jTextFieldT12;
    private javax.swing.JTextField jTextFieldT14;
    private javax.swing.JTextField jTextFieldT16;
    private javax.swing.JTextField jTextFieldT18;
    private javax.swing.JTextField jTextFieldT20;
    private javax.swing.JTextField jTextFieldT22;
    private javax.swing.JTextField jTextFieldT6;
    private javax.swing.JTextField jTextFieldT8;
    private javax.swing.JTextField jTextFieldTelefonoCliente;
    private javax.swing.JTextField jTextFieldTotalVenta;
    // End of variables declaration//GEN-END:variables
}
