/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Admin.Usuario;

import DAOs.UsuarioDAO;
import Modelos.EntidadUsuario;
import javax.swing.JOptionPane;


public class AdminAgregarUsuario extends javax.swing.JFrame {

    UsuarioDAO uDAO = new UsuarioDAO();
    EntidadUsuario eu = new EntidadUsuario();
    public AdminAgregarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Agregar Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jTextFieldNIT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTelefono2 = new javax.swing.JTextField();
        jTextFieldTelefono1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNomEmer = new javax.swing.JTextField();
        jTextFieldTelEmer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregarUsuario = new javax.swing.JButton();
        jButtonAddCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales PT1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRES*");

        jTextFieldNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombre2KeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N_IDENTIFICACIÓN*");

        jTextFieldNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombre1KeyTyped(evt);
            }
        });

        jTextFieldNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNITActionPerformed(evt);
            }
        });
        jTextFieldNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNITKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDOS*");

        jTextFieldApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellido1KeyTyped(evt);
            }
        });

        jTextFieldApellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellido2KeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EDAD*");

        jTextFieldEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNIT)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombre1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales PT2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DIRECCIÓN*");

        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });
        jTextFieldDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDireccionKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TELÉFONOS*");

        jTextFieldTelefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefono2KeyTyped(evt);
            }
        });

        jTextFieldTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefono1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTextFieldTelefono2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTelefono1)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NOMBRE DE CONTACTO DE EMERGENCIA*");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NÚMERO DE EMERGENCIA*");

        jTextFieldNomEmer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomEmerKeyTyped(evt);
            }
        });

        jTextFieldTelEmer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelEmerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldNomEmer)
            .addComponent(jTextFieldTelEmer)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomEmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jTextFieldTelEmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Campos * son Obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13))))
        );

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Usuario.png"))); // NOI18N
        jLabel1.setText("AGREGAR USUARIO");

        jButtonAgregarUsuario.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAgregarUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAgregarUsuario.setText("AGREGAR");
        jButtonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarUsuarioActionPerformed(evt);
            }
        });

        jButtonAddCancelar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonAddCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddCancelar.setText("VOLVER");
        jButtonAddCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addComponent(jButtonAddCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNITActionPerformed

    private void jButtonAddCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAddCancelarActionPerformed

    private void jButtonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        String nit = jTextFieldNIT.getText();

        if (jTextFieldNIT.getText().equals("") || jTextFieldNombre1.getText().equals("")
                || jTextFieldApellido1.getText().equals("") || jTextFieldEdad.getText().equals("")
                || jTextFieldDireccion.getText().equals("") || jTextFieldTelefono1.getText().equals("")
                || jTextFieldNomEmer.getText().equals("") || jTextFieldTelEmer.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese todos los datos obligatorios");
            jTextFieldEdad.requestFocus();
        } else {

            eu = uDAO.buscar(nit);
            if (eu.getNit() != null) {

                JOptionPane.showMessageDialog(this, "Un usuario con esta identificación ya está registrado");

            } else {

                int vEdad = Integer.parseInt(jTextFieldEdad.getText());
                if (vEdad < 18 || vEdad > 60) {

                    JOptionPane.showMessageDialog(this, "La edad del usuario no es admisible,debe estar entre 18 y 60 años");
                    jTextFieldEdad.requestFocus();

                } else {

                    String telefono = jTextFieldTelefono1.getText();

                    long telValidar = Long.parseLong(telefono);
                    long numMinTel = Long.parseLong("1000000");
                    long numMaxTel = Long.parseLong("9999999");
                    long numMinCel = Long.parseLong("3000000000");
                    long numMaxCel = Long.parseLong("3999999999");

                    if (telValidar < 0 || telValidar > 0 && telValidar < numMinTel
                            || telValidar > numMaxTel && telValidar < numMinCel
                            || telValidar > numMaxCel) {
                        JOptionPane.showMessageDialog(this, "El número de teléfono no es admisible\nEjemplo:\n"
                                + "Celular -> 31412178##\n"
                                + "Teléfono local -> 56278##");
                        jTextFieldTelefono1.requestFocus();

                    } else {

                        String telefonoEmergencia = jTextFieldTelEmer.getText();
                        long telValidarEmer = Long.parseLong(telefonoEmergencia);

                        if (telValidarEmer < 0 || telValidarEmer > 0 && telValidarEmer < numMinTel
                                || telValidarEmer > numMaxTel && telValidarEmer < numMinCel
                                || telValidarEmer > numMaxCel) {
                            JOptionPane.showMessageDialog(this, "El número de teléfono de emergencia no es admisible\nEjemplo:\n"
                                    + "Celular -> 31412178##\n"
                                    + "Teléfono local -> 56278##");
                            jTextFieldTelEmer.requestFocus();

                        } else {
                            agregar();


                        }

                    }

                }

            }

        }


    }//GEN-LAST:event_jButtonAgregarUsuarioActionPerformed

    private void jTextFieldEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadKeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldEdadKeyTyped

    private void jTextFieldNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNITKeyTyped
        // TODO add your handling code here:
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
   
    }//GEN-LAST:event_jTextFieldNITKeyTyped

    private void jTextFieldTelefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefono2KeyTyped
          char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldTelefono2KeyTyped

    private void jTextFieldTelEmerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelEmerKeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldTelEmerKeyTyped

    private void jTextFieldNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombre1KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloLetras(evt, v, c);
 
    }//GEN-LAST:event_jTextFieldNombre1KeyTyped

    private void jTextFieldNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombre2KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloLetras(evt, v, c);
        
    }//GEN-LAST:event_jTextFieldNombre2KeyTyped

    private void jTextFieldApellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellido1KeyTyped
                char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloLetras(evt, v, c);
    }//GEN-LAST:event_jTextFieldApellido1KeyTyped

    private void jTextFieldApellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellido2KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloLetras(evt, v, c);
    }//GEN-LAST:event_jTextFieldApellido2KeyTyped

    private void jTextFieldNomEmerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomEmerKeyTyped
         char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloLetrasConEspacio(evt, v, c);
    }//GEN-LAST:event_jTextFieldNomEmerKeyTyped

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccionKeyTyped
              char v = evt.getKeyChar();
        
        mayusculas(evt, v);
    }//GEN-LAST:event_jTextFieldDireccionKeyTyped

    private void jTextFieldTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefono1KeyTyped
      char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldTelefono1KeyTyped

    public void soloLetras(java.awt.event.KeyEvent evt, char v, int c){
        
        if (Character.isLowerCase(v)){
        
           evt.setKeyChar(Character.toUpperCase(v));
            
        }      
        if (Character.isDigit(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo letras");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        } 
        
    }
    
    public void mayusculas(java.awt.event.KeyEvent evt, char v){
          if (Character.isLowerCase(v)){
        
           evt.setKeyChar(Character.toUpperCase(v));
            
        } 
    }
    
       public void soloLetrasConEspacio(java.awt.event.KeyEvent evt, char v, int c){
        
        if (Character.isLowerCase(v)){
        
           evt.setKeyChar(Character.toUpperCase(v));
            
        }      
        if (Character.isDigit(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo letras");
            
        }
    
       if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        } 
        
    }
   public void soloNumeros(java.awt.event.KeyEvent evt, char v, int c){
    

        if (Character.isLetter(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo números");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        }
    
    
    }
    
    
    public void limpiar(){
    
        jTextFieldNIT.setText("");
        jTextFieldNombre1.setText("");
        jTextFieldNombre2.setText("");
        jTextFieldApellido1.setText("");
        jTextFieldApellido2.setText("");
        jTextFieldEdad.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldTelefono1.setText("");
        jTextFieldTelefono2.setText("");
        jTextFieldNomEmer.setText("");
        jTextFieldTelEmer.setText("");
    }
    public void agregar(){
        
        
        if (jTextFieldTelefono2.getText().equals("")){
        String nit = jTextFieldNIT.getText();
        String nombre1 = jTextFieldNombre1.getText();
        String nombre2 = jTextFieldNombre2.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        int edad = Integer.valueOf(jTextFieldEdad.getText());
        String direccion = jTextFieldDireccion.getText();
        String telefono1 = jTextFieldTelefono1.getText();
        String telefono2 = jTextFieldTelefono2.getText();
        String contacto = jTextFieldNomEmer.getText();
            String telContacto = jTextFieldTelEmer.getText();
            String contrasena = nit;

            Object[] ob = new Object[12];

            ob[0] = nit;
            ob[1] = nombre1;
            ob[2] = nombre2;
            ob[3] = apellido1;
            ob[4] = apellido2;
            ob[5] = telefono1;
            ob[6] = telefono2;
            ob[7] = direccion;
            ob[8] = contacto;
            ob[9] = telContacto;
            ob[10] = contrasena;
            ob[11] = edad;

            uDAO.agregar(ob);
            JOptionPane.showMessageDialog(this, "Usuario agregado");
            limpiar();

        } else {

            String telefono2 = jTextFieldTelefono2.getText();

            long telValidar = Long.parseLong(telefono2);
            long numMinTel = Long.parseLong("1000000");
            long numMaxTel = Long.parseLong("9999999");
            long numMinCel = Long.parseLong("3000000000");
            long numMaxCel = Long.parseLong("3999999999");

            if (telValidar < 0 || telValidar > 0 && telValidar < numMinTel
                    || telValidar > numMaxTel && telValidar < numMinCel
                    || telValidar > numMaxCel) {
                JOptionPane.showMessageDialog(this, "El número de teléfono opcional no es admisible\nEjemplo:\n"
                        + "Celular -> 31412178##\n"
                        + "Teléfono local -> 56278##");
                jTextFieldTelefono2.requestFocus();

            } else {
                
        String nit = jTextFieldNIT.getText();
        String nombre1 = jTextFieldNombre1.getText();
        String nombre2 = jTextFieldNombre2.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        int edad = Integer.valueOf(jTextFieldEdad.getText());
        String direccion = jTextFieldDireccion.getText();
        String telefono1 = jTextFieldTelefono1.getText();
        String telefonoOp = jTextFieldTelefono2.getText();
        String contacto = jTextFieldNomEmer.getText();
            String telContacto = jTextFieldTelEmer.getText();
            String contrasena = nit;

            Object[] ob = new Object[12];

            ob[0] = nit;
            ob[1] = nombre1;
            ob[2] = nombre2;
            ob[3] = apellido1;
            ob[4] = apellido2;
            ob[5] = telefono1;
            ob[6] = telefonoOp;
            ob[7] = direccion;
            ob[8] = contacto;
            ob[9] = telContacto;
            ob[10] = contrasena;
            ob[11] = edad;

            uDAO.agregar(ob);
                JOptionPane.showMessageDialog(this, "Usuario agregado");
                limpiar();
                
            }
            }
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCancelar;
    private javax.swing.JButton jButtonAgregarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNIT;
    private javax.swing.JTextField jTextFieldNomEmer;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre2;
    private javax.swing.JTextField jTextFieldTelEmer;
    private javax.swing.JTextField jTextFieldTelefono1;
    private javax.swing.JTextField jTextFieldTelefono2;
    // End of variables declaration//GEN-END:variables
}
