/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Vendedor.Usuario;

import DAOs.UsuarioDAO;
import Modelos.EntidadUsuario;
import Vistas.AutenticacionMenu.FormMenuVendedor;
import javax.swing.JOptionPane;


public class VendedorCambiarContra extends javax.swing.JFrame {

    UsuarioDAO uDAO = new UsuarioDAO();
    EntidadUsuario eu = new EntidadUsuario();
    public VendedorCambiarContra() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cambiar Contraseña");
        jPasswordFieldContrasenaActual.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButtonVerificarContra = new javax.swing.JButton();
        jPasswordFieldContrasenaActual = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordFieldNuevaContrasena = new javax.swing.JPasswordField();
        jPasswordFieldConfirmarNuevaContrasena = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNit = new javax.swing.JTextField();
        jButtonModificarContraseña = new javax.swing.JButton();
        jButtonMCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Usuario.png"))); // NOI18N
        jLabel1.setText("CAMBIAR CONTRASEÑA");

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales PT1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRES");

        jTextFieldNombre2.setEditable(false);
        jTextFieldNombre2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldNombre2.setForeground(new java.awt.Color(0, 102, 153));

        jTextFieldNombre1.setEditable(false);
        jTextFieldNombre1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldNombre1.setForeground(new java.awt.Color(0, 102, 153));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDOS");

        jTextFieldApellido1.setEditable(false);
        jTextFieldApellido1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldApellido1.setForeground(new java.awt.Color(0, 102, 153));

        jTextFieldApellido2.setEditable(false);
        jTextFieldApellido2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldApellido2.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldApellido2)
                    .addComponent(jTextFieldApellido1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verificar contraseña actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONTRASEÑA");

        jButtonVerificarContra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVerificarContra.setText("VERIFICAR");
        jButtonVerificarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVerificarContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldContrasenaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordFieldContrasenaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVerificarContra, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NUEVA CONTRASEÑA");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CONFIRME CONTRASEÑA");

        jPasswordFieldNuevaContrasena.setEditable(false);

        jPasswordFieldConfirmarNuevaContrasena.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(0, 240, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldNuevaContrasena)
                    .addComponent(jPasswordFieldConfirmarNuevaContrasena))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(13, 13, 13)
                .addComponent(jPasswordFieldNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldConfirmarNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N_IDENTIFICACIÓN");

        jTextFieldNit.setEditable(false);
        jTextFieldNit.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldNit.setForeground(new java.awt.Color(0, 102, 153));
        jTextFieldNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNitKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        jButtonModificarContraseña.setBackground(new java.awt.Color(204, 255, 204));
        jButtonModificarContraseña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonModificarContraseña.setText("CAMBIAR CONTRASEÑA");
        jButtonModificarContraseña.setEnabled(false);
        jButtonModificarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarContraseñaActionPerformed(evt);
            }
        });

        jButtonMCancelar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonMCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonMCancelar.setText("VOLVER");
        jButtonMCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarContraseñaActionPerformed
        if (jPasswordFieldNuevaContrasena.getText().equals("")||jPasswordFieldConfirmarNuevaContrasena.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar la nueva contraseña");
            jPasswordFieldNuevaContrasena.requestFocus();
        }else{
        modificarContra();
        }
        
        

    }//GEN-LAST:event_jButtonModificarContraseñaActionPerformed

    private void jButtonMCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMCancelarActionPerformed
        // TODO add your handling code here:
        FormMenuVendedor abrir = new FormMenuVendedor();
        abrir.setVisible(true);
        abrir.jTextFieldIdUsuario.setText(jTextFieldNit.getText());
        abrir.jTextFieldNombre.setText(jTextFieldNombre1.getText() + " " + jTextFieldApellido1.getText());
        abrir.jTextFieldRol.setText("Vendedor");
        this.dispose();
    }//GEN-LAST:event_jButtonMCancelarActionPerformed

    private void jButtonVerificarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarContraActionPerformed
        // TODO add your handling code here:
        validarContrasena();
    }//GEN-LAST:event_jButtonVerificarContraActionPerformed

    private void jTextFieldNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNitKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNitKeyTyped

    public void validarContrasena(){
        String nit = jTextFieldNit.getText();
        String contrasena = jPasswordFieldContrasenaActual.getText();
        
        if(jTextFieldNit.getText().equals("")||jPasswordFieldContrasenaActual.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar los datos en la caja de texto");
            jPasswordFieldContrasenaActual.requestFocus();
        }else{
             eu = uDAO.validarUsuario(nit, contrasena);
             if (eu.getNit() != null && eu.getContrasena()!= null){
                 
                 jButtonModificarContraseña.setEnabled(true);
                 jPasswordFieldNuevaContrasena.setEditable(true);
                 jPasswordFieldConfirmarNuevaContrasena.setEditable(true);
                 jPasswordFieldContrasenaActual.setEditable(false);
                 jButtonVerificarContra.setEnabled(false);
             }else{
                 JOptionPane.showMessageDialog(this,"El usuario o la contraseña son incorrectos");
                 jPasswordFieldContrasenaActual.requestFocus();
             }
        }
    
    }
    public void buscar(){
        
          String nit = jTextFieldNit.getText();
        
        if(jTextFieldNit.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar los datos en la caja de texto");
            jTextFieldNit.requestFocus();
        }else{
            
            eu = uDAO.buscar(nit);
            if (eu.getNit() != null ){
                jTextFieldNombre1.setText(eu.getPrimerNombre());
                jTextFieldNombre2.setText(eu.getSegundoNombre());
                jTextFieldApellido1.setText(eu.getPrimerApellido());
                jTextFieldApellido2.setText(eu.getSegundoApellido());

            }else{
                 JOptionPane.showMessageDialog(this,"La identificación que ingreso no está registrada");
                 jTextFieldNit.requestFocus();
             }
    }
    }
    
    public void modificarContra(){
        String nuevaContrasena = jPasswordFieldNuevaContrasena.getText();
        String confirmarContrasena = jPasswordFieldConfirmarNuevaContrasena.getText();

        String nit = jTextFieldNit.getText();
        if(nuevaContrasena.equals(confirmarContrasena)){       
            
        Object[]ob = new Object[2];
        ob[0]= nuevaContrasena;
        ob[1]= nit;   
        
        uDAO.modificarContrasena(ob);
        JOptionPane.showMessageDialog(this, "Contraseña actualizada");
        jPasswordFieldContrasenaActual.setEditable(true);
        jButtonVerificarContra.setEnabled(true);
        jButtonModificarContraseña.setEnabled(false);
        jPasswordFieldNuevaContrasena.setEditable(false);
        jPasswordFieldConfirmarNuevaContrasena.setEditable(false);
        limpiar();
        }else{
             JOptionPane.showMessageDialog(this,"Las contraseñas no concuerdan");
                 jPasswordFieldNuevaContrasena.requestFocus();
        }
   
        
        
        
    }
    
    public void limpiar(){
        jPasswordFieldNuevaContrasena.setText("");
        jPasswordFieldConfirmarNuevaContrasena.setText("");
        jPasswordFieldContrasenaActual.setText("");
        
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMCancelar;
    private javax.swing.JButton jButtonModificarContraseña;
    private javax.swing.JButton jButtonVerificarContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldConfirmarNuevaContrasena;
    private javax.swing.JPasswordField jPasswordFieldContrasenaActual;
    private javax.swing.JPasswordField jPasswordFieldNuevaContrasena;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    public javax.swing.JTextField jTextFieldNit;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre2;
    // End of variables declaration//GEN-END:variables
}
