/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Admin.Producto;

import DAOs.ProductoDAO;
import Modelos.EntidadProducto;

import javax.swing.JOptionPane;


public class AdminAgregarProducto extends javax.swing.JFrame {

    ProductoDAO pDAO = new ProductoDAO();
    EntidadProducto ep = new EntidadProducto();
    public AdminAgregarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Agregar Producto");
        this.generarCodigoProducto();
        jTextFieldNombre.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldCosto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldT6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldT8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldT10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldT12 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldT14 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldT16 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldT18 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldT20 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldT22 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregarUsuario = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("NOMBRE DEL PRODUCTO*");

        jLabel3.setText("PRECIO DE VENTA*");

        jLabel4.setText("COSTO (Promedio)*");

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });

        jTextFieldCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostoKeyTyped(evt);
            }
        });

        jLabel15.setText("CÓDIGO*");

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(0, 102, 153));
        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jLabel16.setText("Campos con * son obligatorios ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCosto, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidades por talla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel5.setText("TALLAS*");

        jLabel6.setText("T6");

        jTextFieldT6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT6KeyTyped(evt);
            }
        });

        jLabel7.setText("T8");

        jTextFieldT8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT8KeyTyped(evt);
            }
        });

        jLabel8.setText("T10");

        jTextFieldT10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT10KeyTyped(evt);
            }
        });

        jLabel9.setText("T12");

        jTextFieldT12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT12KeyTyped(evt);
            }
        });

        jLabel10.setText("T14");

        jTextFieldT14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT14KeyTyped(evt);
            }
        });

        jLabel11.setText("T16");

        jTextFieldT16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT16KeyTyped(evt);
            }
        });

        jLabel12.setText("T18");

        jTextFieldT18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT18KeyTyped(evt);
            }
        });

        jLabel13.setText("T20");

        jTextFieldT20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT20KeyTyped(evt);
            }
        });

        jLabel14.setText("T22");

        jTextFieldT22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldT22KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldT14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldT12, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(jTextFieldT6)
                                    .addComponent(jTextFieldT8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldT10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldT22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldT20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldT18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldT16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Pantalones.png"))); // NOI18N
        jLabel1.setText("AGREGAR PRODUCTO");

        jButtonAgregarUsuario.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAgregarUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAgregarUsuario.setText("AGREGAR");
        jButtonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarUsuarioActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCancelar.setText("VOLVER");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonCancelarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void generarCodigoProducto(){
    
        String idProducto = pDAO.obtenerIdProducto();
        int idPro;
        if (idProducto.equals("")){
            idPro=0;
        }else{
            idPro = Integer.parseInt(idProducto);
        }
        int incremento = idPro + 1;
        String codigoGenerado = "R"+incremento;
    
        jTextFieldCodigo.setText(codigoGenerado);
    
    }
    
    private void jButtonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarUsuarioActionPerformed

        String codigoP = jTextFieldCodigo.getText();

        if (jTextFieldNombre.getText().equals("") || jTextFieldCodigo.getText().equals("")
                || jTextFieldPrecio.getText().equals("") || jTextFieldCosto.getText().equals("")
                || jTextFieldT6.getText().equals("") || jTextFieldT8.getText().equals("")
                || jTextFieldT10.getText().equals("") || jTextFieldT12.getText().equals("")
                || jTextFieldT14.getText().equals("") || jTextFieldT16.getText().equals("")
                || jTextFieldT18.getText().equals("") || jTextFieldT20.getText().equals("")
                || jTextFieldT22.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Debe ingresar toda la información");

        } else {
            ep = pDAO.buscar(codigoP);
            if (ep.getCodigo() != null) {

                JOptionPane.showMessageDialog(this, "Un producto con este codigo ya fue registrado");

            } else {

                int precioP = Integer.parseInt(jTextFieldPrecio.getText());
                if (precioP < 0 || precioP > 100000) {

                    JOptionPane.showMessageDialog(this, "El precio no debe superar los 100.000$ y no debe ser negativo");
                    jTextFieldPrecio.requestFocus();

                } else {
                    int costoP = Integer.parseInt(jTextFieldCosto.getText());
                    if (costoP < 0 || costoP > 50000) {

                        JOptionPane.showMessageDialog(this, "El costo promedio del producto no debe superar los 50.000$ y no debe ser negativo");
                        jTextFieldCosto.requestFocus();

                    } else {

                        if (costoP >= precioP) {

                            JOptionPane.showMessageDialog(this, "El costo promedio del producto no debe superar al precio de venta");
                            jTextFieldCosto.requestFocus();
                        } else {
                            int T6 = Integer.parseInt(jTextFieldT6.getText());
                            int T8 = Integer.parseInt(jTextFieldT8.getText());
                            int T10 = Integer.parseInt(jTextFieldT10.getText());
                            int T12 = Integer.parseInt(jTextFieldT12.getText());
                            int T14 = Integer.parseInt(jTextFieldT14.getText());
                            int T16 = Integer.parseInt(jTextFieldT16.getText());
                            int T18 = Integer.parseInt(jTextFieldT18.getText());
                            int T20 = Integer.parseInt(jTextFieldT20.getText());
                            int T22 = Integer.parseInt(jTextFieldT22.getText());

                            if (T6 < 0 || T6 > 100 || T8 < 0 || T8 > 100 || T10 < 0 || T10 > 100
                                    || T12 < 0 || T12 > 100 || T14 < 0 || T14 > 100 || T16 < 0 || T16 > 100
                                    || T18 < 0 || T18 > 100 || T20 < 0 || T20 > 100 || T22 < 0 || T22 > 100) {
                                JOptionPane.showMessageDialog(this, "Las cantidades de los productos por talla no debe ser negativa  ni ser superior a 100");
                                jTextFieldCosto.requestFocus();
                            } else {
                                agregar();
                                JOptionPane.showMessageDialog(this, "Producto agregado");
                                limpiar();

                            }

                        }

                    }

                }

            }

        }


    }//GEN-LAST:event_jButtonAgregarUsuarioActionPerformed

        public void limpiar(){
        jTextFieldNombre.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldCosto.setText("");
        jTextFieldT6.setText("");
        jTextFieldT8.setText("");
        jTextFieldT10.setText("");
        jTextFieldT12.setText("");
        jTextFieldT14.setText("");
        jTextFieldT16.setText("");
        jTextFieldT18.setText("");
        jTextFieldT20.setText("");
        jTextFieldT22.setText("");
        
        }
        public void agregar(){
        
        String nombre = jTextFieldNombre.getText();
        String codigo = jTextFieldCodigo.getText();
        int precio = Integer.valueOf(jTextFieldPrecio.getText());
        int costo = Integer.valueOf(jTextFieldCosto.getText());
        int t6 = Integer.valueOf(jTextFieldT6.getText());
        int t8 = Integer.valueOf(jTextFieldT8.getText());
        int t10 = Integer.valueOf(jTextFieldT10.getText());
        int t12 = Integer.valueOf(jTextFieldT12.getText());
        int t14 = Integer.valueOf(jTextFieldT14.getText());
        int t16 = Integer.valueOf(jTextFieldT16.getText());
        int t18 = Integer.valueOf(jTextFieldT18.getText());
        int t20 = Integer.valueOf(jTextFieldT20.getText());
        int t22 = Integer.valueOf(jTextFieldT22.getText());
        int stock = t6+t8+t10+t12+t14+t16+t18+t20+t22;
        
        Object[] ob = new Object[14];
        
        ob[0]= nombre;
        ob[1]= codigo;
        ob[2]= precio;
        ob[3]= costo;
        ob[4]= t6;
        ob[5]= t8;
        ob[6]= t10;
        ob[7]= t12;
        ob[8]= t14;
        ob[9]= t16;
        ob[10]= t18;
        ob[11]= t20;
        ob[12]= t22;
        ob[13]= stock;
        
        
        pDAO.agregar(ob);
        
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        

        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
          char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloLetrasConEspacio(evt, v, c);
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        SoloLetrasNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped
         char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();
        
        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    private void jTextFieldCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostoKeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldCostoKeyTyped

    private void jTextFieldT6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT6KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT6KeyTyped

    private void jTextFieldT8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT8KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT8KeyTyped

    private void jTextFieldT10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT10KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT10KeyTyped

    private void jTextFieldT12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT12KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT12KeyTyped

    private void jTextFieldT14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT14KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT14KeyTyped

    private void jTextFieldT16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT16KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT16KeyTyped

    private void jTextFieldT18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT18KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT18KeyTyped

    private void jTextFieldT20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT20KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT20KeyTyped

    private void jTextFieldT22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldT22KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldT22KeyTyped

    private void jButtonCancelarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarKeyTyped

    public void SoloLetrasNumeros(java.awt.event.KeyEvent evt, char v, int c){
    
        if (Character.isLowerCase(v)) {

            evt.setKeyChar(Character.toUpperCase(v));

        }

        if (Character.isSpaceChar(v)) {

            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");

        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255) {
           
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");

        }
    
    }
        public void soloLetras(java.awt.event.KeyEvent evt, char v, int c){
        
        if (Character.isLowerCase(v)){
        
           evt.setKeyChar(Character.toUpperCase(v));
            
        }      
        if (Character.isDigit(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo letras");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        } 
        
    }
       public void soloLetrasConEspacio(java.awt.event.KeyEvent evt, char v, int c){
        
        if (Character.isLowerCase(v)){
        
           evt.setKeyChar(Character.toUpperCase(v));
            
        }      
        if (Character.isDigit(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo letras");
            
        }

        
       if(c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        } 
        
    }
   public void soloNumeros(java.awt.event.KeyEvent evt, char v, int c){
    

        if (Character.isLetter(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo números");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if(c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        }
    
    
    }
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarUsuario;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldT10;
    private javax.swing.JTextField jTextFieldT12;
    private javax.swing.JTextField jTextFieldT14;
    private javax.swing.JTextField jTextFieldT16;
    private javax.swing.JTextField jTextFieldT18;
    private javax.swing.JTextField jTextFieldT20;
    private javax.swing.JTextField jTextFieldT22;
    private javax.swing.JTextField jTextFieldT6;
    private javax.swing.JTextField jTextFieldT8;
    // End of variables declaration//GEN-END:variables
}
