/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Admin.Producto;

import DAOs.ProductoDAO;
import Modelos.EntidadProducto;
import Vistas.AutenticacionMenu.FormMenuAdmin;
import javax.swing.JOptionPane;

/**
 *
 * @author CAMILO
 */
public class AdminReabastecerProducto extends javax.swing.JFrame {

    ProductoDAO pDAO = new ProductoDAO();
    EntidadProducto ep = new EntidadProducto();
    public AdminReabastecerProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Reabastecer Producto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCAT6 = new javax.swing.JTextField();
        jTextFieldCAT8 = new javax.swing.JTextField();
        jTextFieldCAT10 = new javax.swing.JTextField();
        jTextFieldCAT14 = new javax.swing.JTextField();
        jTextFieldCAT16 = new javax.swing.JTextField();
        jTextFieldCAT18 = new javax.swing.JTextField();
        jTextFieldCAT20 = new javax.swing.JTextField();
        jTextFieldCAT22 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTT6 = new javax.swing.JTextField();
        jTextFieldTT8 = new javax.swing.JTextField();
        jTextFieldTT10 = new javax.swing.JTextField();
        jTextFieldTT12 = new javax.swing.JTextField();
        jTextFieldTT14 = new javax.swing.JTextField();
        jTextFieldTT16 = new javax.swing.JTextField();
        jTextFieldTT18 = new javax.swing.JTextField();
        jTextFieldTT20 = new javax.swing.JTextField();
        jTextFieldTT22 = new javax.swing.JTextField();
        jSpinnerCAA6 = new javax.swing.JSpinner();
        jSpinnerCAA8 = new javax.swing.JSpinner();
        jSpinnerCAA10 = new javax.swing.JSpinner();
        jSpinnerCAA12 = new javax.swing.JSpinner();
        jSpinnerCAA14 = new javax.swing.JSpinner();
        jSpinnerCAA16 = new javax.swing.JSpinner();
        jSpinnerCAA20 = new javax.swing.JSpinner();
        jSpinnerCAA22 = new javax.swing.JSpinner();
        jTextFieldCAT12 = new javax.swing.JTextField();
        jSpinnerCAA18 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonPreReabastecer = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonReabastecer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel19.setText("T20");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidades por talla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel5.setText("TALLAS");

        jLabel6.setText("T6");

        jLabel7.setText("T8");

        jLabel8.setText("T10");

        jLabel9.setText("T12");

        jLabel10.setText("T14");

        jLabel15.setText("CANT.ACTUAL");

        jLabel16.setText("T16");

        jLabel17.setText("T18");

        jLabel18.setText("T20");

        jLabel20.setText("T22");

        jTextFieldCAT6.setEditable(false);
        jTextFieldCAT6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT6.setForeground(new java.awt.Color(0, 102, 153));

        jTextFieldCAT8.setEditable(false);
        jTextFieldCAT8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT8.setForeground(new java.awt.Color(0, 102, 153));
        jTextFieldCAT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCAT8ActionPerformed(evt);
            }
        });

        jTextFieldCAT10.setEditable(false);
        jTextFieldCAT10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT10.setForeground(new java.awt.Color(0, 102, 153));
        jTextFieldCAT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCAT10ActionPerformed(evt);
            }
        });

        jTextFieldCAT14.setEditable(false);
        jTextFieldCAT14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT14.setForeground(new java.awt.Color(0, 102, 153));

        jTextFieldCAT16.setEditable(false);
        jTextFieldCAT16.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT16.setForeground(new java.awt.Color(0, 102, 153));

        jTextFieldCAT18.setEditable(false);
        jTextFieldCAT18.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT18.setForeground(new java.awt.Color(0, 102, 153));

        jTextFieldCAT20.setEditable(false);
        jTextFieldCAT20.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT20.setForeground(new java.awt.Color(0, 102, 153));

        jTextFieldCAT22.setEditable(false);
        jTextFieldCAT22.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT22.setForeground(new java.awt.Color(0, 102, 153));

        jLabel3.setText("CANT.ADD");

        jLabel4.setText("TOTAL ");

        jTextFieldTT6.setEditable(false);

        jTextFieldTT8.setEditable(false);

        jTextFieldTT10.setEditable(false);

        jTextFieldTT12.setEditable(false);

        jTextFieldTT14.setEditable(false);

        jTextFieldTT16.setEditable(false);

        jTextFieldTT18.setEditable(false);

        jTextFieldTT20.setEditable(false);
        jTextFieldTT20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTT20ActionPerformed(evt);
            }
        });

        jTextFieldTT22.setEditable(false);
        jTextFieldTT22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTT22ActionPerformed(evt);
            }
        });

        jSpinnerCAA6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA6KeyTyped(evt);
            }
        });

        jSpinnerCAA8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA8KeyTyped(evt);
            }
        });

        jSpinnerCAA10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA10KeyTyped(evt);
            }
        });

        jSpinnerCAA12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA12KeyTyped(evt);
            }
        });

        jSpinnerCAA14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA14KeyTyped(evt);
            }
        });

        jSpinnerCAA16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA16KeyTyped(evt);
            }
        });

        jSpinnerCAA20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA20KeyTyped(evt);
            }
        });

        jSpinnerCAA22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA22KeyTyped(evt);
            }
        });

        jTextFieldCAT12.setEditable(false);
        jTextFieldCAT12.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextFieldCAT12.setForeground(new java.awt.Color(0, 102, 153));
        jTextFieldCAT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCAT12ActionPerformed(evt);
            }
        });

        jSpinnerCAA18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinnerCAA18KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCAT18)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCAT6)
                    .addComponent(jTextFieldCAT8)
                    .addComponent(jTextFieldCAT10)
                    .addComponent(jTextFieldCAT12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCAT14)
                    .addComponent(jTextFieldCAT16)
                    .addComponent(jTextFieldCAT20)
                    .addComponent(jTextFieldCAT22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerCAA6)
                            .addComponent(jSpinnerCAA8)
                            .addComponent(jSpinnerCAA10)
                            .addComponent(jSpinnerCAA12)
                            .addComponent(jSpinnerCAA16)
                            .addComponent(jSpinnerCAA20)
                            .addComponent(jSpinnerCAA22)
                            .addComponent(jSpinnerCAA18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jTextFieldTT10)
                            .addComponent(jTextFieldTT12)
                            .addComponent(jTextFieldTT16)
                            .addComponent(jTextFieldTT20)
                            .addComponent(jTextFieldTT22)
                            .addComponent(jTextFieldTT6)
                            .addComponent(jTextFieldTT8)
                            .addComponent(jTextFieldTT18, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSpinnerCAA14, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTT14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCAT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCAA6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCAT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCAA8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCAT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCAA10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerCAA12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCAT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jTextFieldTT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCAT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCAA14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCAA16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCAT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCAT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jSpinnerCAA18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCAA20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCAT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCAT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCAA22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel2.setText("CÓDIGO PRODUCTO");

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonPreReabastecer.setBackground(new java.awt.Color(153, 204, 255));
        jButtonPreReabastecer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPreReabastecer.setText("PREVISUALIZAR REABASTECIMIENTO");
        jButtonPreReabastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreReabastecerActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCancelar.setText("VOLVER");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonReabastecer.setBackground(new java.awt.Color(205, 255, 204));
        jButtonReabastecer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonReabastecer.setText("REABASTECER");
        jButtonReabastecer.setEnabled(false);
        jButtonReabastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReabastecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPreReabastecer, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jButtonReabastecer, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButtonPreReabastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReabastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Pantalones.png"))); // NOI18N
        jLabel1.setText("REABASTECER PRODUCTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCAT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCAT8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCAT8ActionPerformed

    private void jTextFieldCAT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCAT10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCAT10ActionPerformed

    private void jTextFieldTT22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTT22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTT22ActionPerformed

    private void jTextFieldTT20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTT20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTT20ActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonPreReabastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreReabastecerActionPerformed
        // TODO add your handling code here:
        if (jTextFieldCodigo.getText().equals("")||jTextFieldCAT6.getText().equals("")
               ||jSpinnerCAA6.getValue()==null){
            JOptionPane.showMessageDialog(this,"Debe debe ingresar los datos");

        
        }else{
         preReabastecer();
        }
       
    }//GEN-LAST:event_jButtonPreReabastecerActionPerformed

    private void jButtonReabastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReabastecerActionPerformed
      
        reabastecer();
        JOptionPane.showMessageDialog(this, "Producto Reabastecido");
        jButtonReabastecer.setEnabled(false);
    }//GEN-LAST:event_jButtonReabastecerActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldCAT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCAT12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCAT12ActionPerformed

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        // TODO add your handling code here:
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        SoloLetrasNumeros(evt, v, c);
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jSpinnerCAA6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA6KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA6KeyTyped

    private void jSpinnerCAA8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA8KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA8KeyTyped

    private void jSpinnerCAA10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA10KeyTyped
       char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA10KeyTyped

    private void jSpinnerCAA12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA12KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA12KeyTyped

    private void jSpinnerCAA14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA14KeyTyped
       char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA14KeyTyped

    private void jSpinnerCAA16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA16KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA16KeyTyped

    private void jSpinnerCAA18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA18KeyTyped
        char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA18KeyTyped

    private void jSpinnerCAA20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA20KeyTyped
       char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA20KeyTyped

    private void jSpinnerCAA22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerCAA22KeyTyped
       char v = evt.getKeyChar();
        int c = (int) evt.getKeyChar();

        soloNumeros(evt, v, c);
    }//GEN-LAST:event_jSpinnerCAA22KeyTyped

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed
        public void SoloLetrasNumeros(java.awt.event.KeyEvent evt, char v, int c){
    
        if (Character.isLowerCase(v)) {

            evt.setKeyChar(Character.toUpperCase(v));

        }

        if (Character.isSpaceChar(v)) {

            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");

        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");

        }
    
    }
           public void soloNumeros(java.awt.event.KeyEvent evt, char v, int c){
    

        if (Character.isLetter(v)){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "Digita solo números");
            
        }
        if (Character.isSpaceChar(v)){
        
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No ingrese espacios en blanco");
            
        }
        if (c > 32 && c <= 47 || c >= 58 && c <= 64 || c >= 91 && c <= 96 || c >= 123 && c <= 208 || c >= 210 && c <= 240 || c >= 242 && c <=255){
        
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "No ingrese caracteres especiales");
            
        }
    
    
    }
    public void reabastecer(){
    
        String codigo = jTextFieldCodigo.getText();
        int TT6 = Integer.valueOf(jTextFieldTT6.getText());
        int TT8 = Integer.valueOf(jTextFieldTT8.getText());
        int TT10 = Integer.valueOf(jTextFieldTT10.getText());
        int TT12 = Integer.valueOf(jTextFieldTT12.getText());
        int TT14 = Integer.valueOf(jTextFieldTT14.getText());
        int TT16 = Integer.valueOf(jTextFieldTT16.getText());
        int TT18 = Integer.valueOf(jTextFieldTT18.getText());
        int TT20 = Integer.valueOf(jTextFieldTT20.getText());
        int TT22 = Integer.valueOf(jTextFieldTT22.getText());
        int stock = TT6+TT8+TT10+TT12+TT14+TT16+TT18+TT20+TT22;
        if(jTextFieldCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el código en la caja de texto");
            jTextFieldCodigo.requestFocus();
        }else{
            
        Object[] ob = new Object[11];
        
        ob[0]= TT6;
        ob[1]= TT8;
        ob[2]= TT10;
        ob[3]= TT12;
        ob[4]= TT14;
        ob[5]= TT16;
        ob[6]= TT18;
        ob[7]= TT20;
        ob[8]= TT22;
        ob[9]= stock;
        ob[10]= codigo;
        
        pDAO.reabastecer(ob);
        
        buscar();
        limpiar();
        
        }
    }
    public void limpiar(){
        jSpinnerCAA6.setValue(0);
        jSpinnerCAA8.setValue(0);
        jSpinnerCAA10.setValue(0);
        jSpinnerCAA12.setValue(0);
        jSpinnerCAA14.setValue(0);
        jSpinnerCAA16.setValue(0);
        jSpinnerCAA18.setValue(0);
        jSpinnerCAA20.setValue(0);
        jSpinnerCAA22.setValue(0);
        
        jTextFieldTT6.setText("");
        jTextFieldTT8.setText("");
        jTextFieldTT10.setText("");
        jTextFieldTT12.setText("");
        jTextFieldTT14.setText("");
        jTextFieldTT16.setText("");
        jTextFieldTT18.setText("");
        jTextFieldTT20.setText("");
        jTextFieldTT22.setText("");
        
    
    }
    
    public void preReabastecer(){
        

   
        // Cantidad actual
        int CatT6 = Integer.valueOf(jTextFieldCAT6.getText());
        int CatT8 = Integer.valueOf(jTextFieldCAT8.getText());
        int CatT10 = Integer.valueOf(jTextFieldCAT10.getText());
        int CatT12 = Integer.valueOf(jTextFieldCAT12.getText());
        int CatT14 = Integer.valueOf(jTextFieldCAT14.getText());
        int CatT16 = Integer.valueOf(jTextFieldCAT16.getText());
        int CatT18 = Integer.valueOf(jTextFieldCAT18.getText());
        int CatT20 = Integer.valueOf(jTextFieldCAT20.getText());
        int CatT22 = Integer.valueOf(jTextFieldCAT22.getText());
        // Cantidad add
        int CadT6 = (int) jSpinnerCAA6.getValue();
        int CadT8 = (int) jSpinnerCAA8.getValue();
        int CadT10 = (int) jSpinnerCAA10.getValue();
        int CadT12 = (int) jSpinnerCAA12.getValue();
        int CadT14 = (int) jSpinnerCAA14.getValue();
        int CadT16 = (int) jSpinnerCAA16.getValue();
        int CadT18 = (int) jSpinnerCAA18.getValue();
        int CadT20 = (int) jSpinnerCAA20.getValue();
        int CadT22 = (int) jSpinnerCAA22.getValue();
        // Pre suma
        if(CadT6 < 0 || CadT8 < 0 ||CadT10 <0
                ||CadT12 < 0 || CadT14 < 0 ||CadT16 < 0
                ||CadT18 < 0 || CadT20 < 0 ||CadT22 < 0){
            
            JOptionPane.showMessageDialog(this, "Ninguna cantidad por talla puede ser negativa");
            jSpinnerCAA6.requestFocus();
            jButtonReabastecer.setEnabled(false);
        }else{
            
        int TT6 = CatT6 + CadT6;
        int TT8 = CatT8 + CadT8;
        int TT10 = CatT10 + CadT10;
        int TT12 = CatT12 + CadT12;
        int TT14 = CatT14 + CadT14;
        int TT16 = CatT16 + CadT16;
        int TT18 = CatT18 + CadT18;
        int TT20 = CatT20 + CadT20;
        int TT22 = CatT22 + CadT22;
        
        if(TT6 > 100 || TT8 > 100 || TT10 > 100
                ||TT12 > 100 || TT14 > 100 || TT16 > 100
                ||TT18 > 100 || TT20 > 100 || TT22 > 100){
                    JOptionPane.showMessageDialog(this, "No se puede sobrepasar 100 unidades por talla");
                    jSpinnerCAA6.requestFocus();
                    jButtonReabastecer.setEnabled(false);
            
        }else{
        jTextFieldTT6.setText(String.valueOf(TT6));
        jTextFieldTT8.setText(String.valueOf(TT8));
        jTextFieldTT10.setText(String.valueOf(TT10));
        jTextFieldTT12.setText(String.valueOf(TT12));
        jTextFieldTT14.setText(String.valueOf(TT14));
        jTextFieldTT16.setText(String.valueOf(TT16));
        jTextFieldTT18.setText(String.valueOf(TT18));
        jTextFieldTT20.setText(String.valueOf(TT20));
        jTextFieldTT22.setText(String.valueOf(TT22));
        
        jButtonReabastecer.setEnabled(true);
        
        
        }
        
        
        }
        

        
    
        
        
        
     
        
    }
        public void buscar(){
            
         String codigo = jTextFieldCodigo.getText();
         
        if(jTextFieldCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el código en la caja de texto");
            jTextFieldCodigo.requestFocus();
        }else{
            
            ep = pDAO.buscar(codigo);
            if (ep.getCodigo()!= null ){
                jTextFieldCAT6.setText(String.valueOf(ep.getT6()));
                jTextFieldCAT8.setText(String.valueOf(ep.getT8()));
                jTextFieldCAT10.setText(String.valueOf(ep.getT10()));
                jTextFieldCAT12.setText(String.valueOf(ep.getT12()));
                jTextFieldCAT14.setText(String.valueOf(ep.getT14()));
                jTextFieldCAT16.setText(String.valueOf(ep.getT16()));
                jTextFieldCAT18.setText(String.valueOf(ep.getT18()));
                jTextFieldCAT20.setText(String.valueOf(ep.getT20()));
                jTextFieldCAT22.setText(String.valueOf(ep.getT22()));
                jTextFieldCodigo.setEditable(false);
  
            }else{
                 JOptionPane.showMessageDialog(this,"El código que ingreso no está registrado");
                 jTextFieldCodigo.requestFocus();
             }
        } 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPreReabastecer;
    private javax.swing.JButton jButtonReabastecer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinnerCAA10;
    private javax.swing.JSpinner jSpinnerCAA12;
    private javax.swing.JSpinner jSpinnerCAA14;
    private javax.swing.JSpinner jSpinnerCAA16;
    private javax.swing.JSpinner jSpinnerCAA18;
    private javax.swing.JSpinner jSpinnerCAA20;
    private javax.swing.JSpinner jSpinnerCAA22;
    private javax.swing.JSpinner jSpinnerCAA6;
    private javax.swing.JSpinner jSpinnerCAA8;
    private javax.swing.JTextField jTextFieldCAT10;
    private javax.swing.JTextField jTextFieldCAT12;
    private javax.swing.JTextField jTextFieldCAT14;
    private javax.swing.JTextField jTextFieldCAT16;
    private javax.swing.JTextField jTextFieldCAT18;
    private javax.swing.JTextField jTextFieldCAT20;
    private javax.swing.JTextField jTextFieldCAT22;
    private javax.swing.JTextField jTextFieldCAT6;
    private javax.swing.JTextField jTextFieldCAT8;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldTT10;
    private javax.swing.JTextField jTextFieldTT12;
    private javax.swing.JTextField jTextFieldTT14;
    private javax.swing.JTextField jTextFieldTT16;
    private javax.swing.JTextField jTextFieldTT18;
    private javax.swing.JTextField jTextFieldTT20;
    private javax.swing.JTextField jTextFieldTT22;
    private javax.swing.JTextField jTextFieldTT6;
    private javax.swing.JTextField jTextFieldTT8;
    // End of variables declaration//GEN-END:variables
}
