package Vistas.AutenticacionMenu;

import Vistas.Admin.Devoluciones.AdminRealizarDevolucion;
import Vistas.Admin.Producto.AdminAgregarProducto;
import Vistas.Admin.Producto.AdminBuscarProducto;
import Vistas.Admin.Producto.AdminHDProducto;
import Vistas.Admin.Producto.AdminModificarProducto;
import Vistas.Admin.Producto.AdminReabastecerProducto;
import Vistas.Admin.Producto.AdminVerPerdidas;
import Vistas.Admin.Usuario.AdminAgregarUsuario;
import Vistas.Admin.Usuario.AdminBuscarUsuario;
import Vistas.Admin.Usuario.AdminHDUsuario;
import Vistas.Admin.Usuario.AdminModificarUsuario;
import Vistas.Admin.Ventas.AdminConsultarVentas;
import Vistas.Admin.Ventas.AdminRealizarVentas;


public class FormMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuAdmin
     */
    
    
    public FormMenuAdmin() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Menú Administrador");
        
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldIdUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRol = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        AdminMenu = new javax.swing.JMenu();
        MenuSalir = new javax.swing.JMenuItem();
        AdminInventario = new javax.swing.JMenu();
        jMenuAgregarProducto = new javax.swing.JMenuItem();
        jMenuBuscarProducto = new javax.swing.JMenuItem();
        jMenuHDProducto = new javax.swing.JMenuItem();
        jMenuModificarProducto = new javax.swing.JMenuItem();
        jMenuReabastecerProducto = new javax.swing.JMenuItem();
        jMenuVerPerdida = new javax.swing.JMenuItem();
        AdminUsuarios = new javax.swing.JMenu();
        jMenuAddUsuario = new javax.swing.JMenuItem();
        jMenuModificarUsuario = new javax.swing.JMenuItem();
        jMenuBuscarUsuario = new javax.swing.JMenuItem();
        jMenuHDUsuario = new javax.swing.JMenuItem();
        AdminVentas = new javax.swing.JMenu();
        jMenuRealizarVenta = new javax.swing.JMenuItem();
        jMenuConsultarVentas = new javax.swing.JMenuItem();
        AdminDevoluciones = new javax.swing.JMenu();
        jMenuDevolucion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jTextFieldIdUsuario.setEditable(false);

        jLabel1.setText("Identificación");

        jLabel2.setText("Nombre");

        jTextFieldNombre.setEditable(false);

        jLabel3.setText("Rol");

        jTextFieldRol.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRol)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        AdminMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu.png"))); // NOI18N
        AdminMenu.setText("Menú");

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        AdminMenu.add(MenuSalir);

        jMenuBar1.add(AdminMenu);

        AdminInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Pantalones.png"))); // NOI18N
        AdminInventario.setText("Inventario");

        jMenuAgregarProducto.setText("Agregar producto");
        jMenuAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarProductoActionPerformed(evt);
            }
        });
        AdminInventario.add(jMenuAgregarProducto);

        jMenuBuscarProducto.setText("Buscar producto");
        jMenuBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarProductoActionPerformed(evt);
            }
        });
        AdminInventario.add(jMenuBuscarProducto);

        jMenuHDProducto.setText("Hablilitar/Deshabilitar producto");
        jMenuHDProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHDProductoActionPerformed(evt);
            }
        });
        AdminInventario.add(jMenuHDProducto);

        jMenuModificarProducto.setText("Modificar producto");
        jMenuModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarProductoActionPerformed(evt);
            }
        });
        AdminInventario.add(jMenuModificarProducto);

        jMenuReabastecerProducto.setText("Reabastecer producto");
        jMenuReabastecerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReabastecerProductoActionPerformed(evt);
            }
        });
        AdminInventario.add(jMenuReabastecerProducto);

        jMenuVerPerdida.setText("Ver perdidas");
        jMenuVerPerdida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerPerdidaActionPerformed(evt);
            }
        });
        AdminInventario.add(jMenuVerPerdida);

        jMenuBar1.add(AdminInventario);

        AdminUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Usuario.png"))); // NOI18N
        AdminUsuarios.setText("Usuarios");

        jMenuAddUsuario.setText("Agregar usuario");
        jMenuAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddUsuarioActionPerformed(evt);
            }
        });
        AdminUsuarios.add(jMenuAddUsuario);

        jMenuModificarUsuario.setText("Modificar usuario");
        jMenuModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarUsuarioActionPerformed(evt);
            }
        });
        AdminUsuarios.add(jMenuModificarUsuario);

        jMenuBuscarUsuario.setText("Buscar usuarios");
        jMenuBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarUsuarioActionPerformed(evt);
            }
        });
        AdminUsuarios.add(jMenuBuscarUsuario);

        jMenuHDUsuario.setText("Habilitar/Deshabilitar usuario");
        jMenuHDUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHDUsuarioActionPerformed(evt);
            }
        });
        AdminUsuarios.add(jMenuHDUsuario);

        jMenuBar1.add(AdminUsuarios);

        AdminVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Ventas.png"))); // NOI18N
        AdminVentas.setText("Ventas");

        jMenuRealizarVenta.setText("Realizar venta");
        jMenuRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRealizarVentaActionPerformed(evt);
            }
        });
        AdminVentas.add(jMenuRealizarVenta);

        jMenuConsultarVentas.setText("Consultar ventas");
        jMenuConsultarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarVentasActionPerformed(evt);
            }
        });
        AdminVentas.add(jMenuConsultarVentas);

        jMenuBar1.add(AdminVentas);

        AdminDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Devolucion.png"))); // NOI18N
        AdminDevoluciones.setText("Devoluciones");

        jMenuDevolucion.setText("Realizar Devolución");
        jMenuDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDevolucionActionPerformed(evt);
            }
        });
        AdminDevoluciones.add(jMenuDevolucion);

        jMenuBar1.add(AdminDevoluciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        // TODO add your handling code here:
        FormLogin abrir = new FormLogin();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void jMenuAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddUsuarioActionPerformed
        // TODO add your handling code here:
        
        AdminAgregarUsuario abrir = new AdminAgregarUsuario();
        abrir.setVisible(true);
      
        
    }//GEN-LAST:event_jMenuAddUsuarioActionPerformed

    private void jMenuModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarUsuarioActionPerformed
        // TODO add your handling code here:
        
        AdminModificarUsuario abrir = new AdminModificarUsuario();
        abrir.setVisible(true);
       
    }//GEN-LAST:event_jMenuModificarUsuarioActionPerformed

    private void jMenuBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        
        AdminBuscarUsuario abrir = new AdminBuscarUsuario();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_jMenuBuscarUsuarioActionPerformed

    private void jMenuHDUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHDUsuarioActionPerformed
        // TODO add your handling code here:
        
        AdminHDUsuario abrir = new AdminHDUsuario();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_jMenuHDUsuarioActionPerformed

    private void jMenuModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarProductoActionPerformed
        // TODO add your handling code here:
        AdminModificarProducto abrir = new AdminModificarProducto();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_jMenuModificarProductoActionPerformed

    private void jMenuAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarProductoActionPerformed
        // TODO add your handling code here:
        AdminAgregarProducto abrir = new AdminAgregarProducto();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_jMenuAgregarProductoActionPerformed

    private void jMenuBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarProductoActionPerformed
        // TODO add your handling code here:
        
        AdminBuscarProducto abrir = new AdminBuscarProducto();
        abrir.setVisible(true);
      
        
    }//GEN-LAST:event_jMenuBuscarProductoActionPerformed

    private void jMenuHDProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHDProductoActionPerformed
        // TODO add your handling code here:
        
        AdminHDProducto abrir = new AdminHDProducto();
        abrir.setVisible(true);
    
    }//GEN-LAST:event_jMenuHDProductoActionPerformed

    private void jMenuReabastecerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReabastecerProductoActionPerformed
        // TODO add your handling code here:
        AdminReabastecerProducto abrir = new AdminReabastecerProducto();
        abrir.setVisible(true);
     
    }//GEN-LAST:event_jMenuReabastecerProductoActionPerformed

    private void jMenuConsultarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarVentasActionPerformed
        // TODO add your handling code here:
        
        AdminConsultarVentas abrir = new AdminConsultarVentas();
        abrir.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuConsultarVentasActionPerformed

    private void jMenuRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRealizarVentaActionPerformed
        // TODO add your handling code here:
        
        AdminRealizarVentas abrir = new AdminRealizarVentas();
        abrir.setVisible(true);
        abrir.jTextFieldNitVendedor.setText(jTextFieldIdUsuario.getText());
        abrir.jTextFieldNombreVendedor.setText(jTextFieldNombre.getText());
        this.dispose();
        
    }//GEN-LAST:event_jMenuRealizarVentaActionPerformed

    private void jMenuDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDevolucionActionPerformed
        // TODO add your handling code here:
        AdminRealizarDevolucion abrir = new AdminRealizarDevolucion();
        abrir.setVisible(true);
       
        
        
    }//GEN-LAST:event_jMenuDevolucionActionPerformed

    private void jMenuVerPerdidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerPerdidaActionPerformed
        AdminVerPerdidas abrir = new AdminVerPerdidas();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuVerPerdidaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdminDevoluciones;
    private javax.swing.JMenu AdminInventario;
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenu AdminUsuarios;
    private javax.swing.JMenu AdminVentas;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuAddUsuario;
    private javax.swing.JMenuItem jMenuAgregarProducto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBuscarProducto;
    private javax.swing.JMenuItem jMenuBuscarUsuario;
    private javax.swing.JMenuItem jMenuConsultarVentas;
    private javax.swing.JMenuItem jMenuDevolucion;
    private javax.swing.JMenuItem jMenuHDProducto;
    private javax.swing.JMenuItem jMenuHDUsuario;
    private javax.swing.JMenuItem jMenuModificarProducto;
    private javax.swing.JMenuItem jMenuModificarUsuario;
    private javax.swing.JMenuItem jMenuReabastecerProducto;
    private javax.swing.JMenuItem jMenuRealizarVenta;
    private javax.swing.JMenuItem jMenuVerPerdida;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldIdUsuario;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldRol;
    // End of variables declaration//GEN-END:variables

}
