-- MySQL Script generated by MySQL Workbench
-- Wed Oct 20 20:44:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(45) NOT NULL,
  `nombre_primero` VARCHAR(45) NOT NULL,
  `apellido_primero` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC),
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`estados` (
  `idestados` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestados`),
  UNIQUE INDEX `idestados_UNIQUE` (`idestados` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `precio_venta` INT NOT NULL,
  `costo` INT NOT NULL,
  `estado_producto` INT NOT NULL DEFAULT '1',
  `t6` INT NOT NULL DEFAULT '0',
  `t8` INT NOT NULL DEFAULT '0',
  `t10` INT NOT NULL DEFAULT '0',
  `t12` INT NOT NULL DEFAULT '0',
  `t14` INT NOT NULL DEFAULT '0',
  `t16` INT NOT NULL DEFAULT '0',
  `t18` INT NOT NULL DEFAULT '0',
  `t20` INT NOT NULL DEFAULT '0',
  `t22` INT NOT NULL DEFAULT '0',
  `stock` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `idproducto_UNIQUE` (`idproducto` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `idestados_idx` (`estado_producto` ASC),
  CONSTRAINT `idestados`
    FOREIGN KEY (`estado_producto`)
    REFERENCES `inventario`.`estados` (`idestados`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`rol_usuario` (
  `idrol_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(45) NOT NULL,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono_1` VARCHAR(45) NOT NULL,
  `telefono_2` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `contacto_emergencia` VARCHAR(45) NOT NULL,
  `telefono_contacto_emergencia` VARCHAR(45) NOT NULL,
  `rol_usuario` INT NOT NULL DEFAULT '2',
  `contrasena` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `estado_usuario` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC),
  INDEX `rol_usuario_idx` (`rol_usuario` ASC),
  INDEX `estado_usuario_idx` (`estado_usuario` ASC),
  CONSTRAINT `estado_usuario`
    FOREIGN KEY (`estado_usuario`)
    REFERENCES `inventario`.`estados` (`idestados`),
  CONSTRAINT `rol_usuario`
    FOREIGN KEY (`rol_usuario`)
    REFERENCES `inventario`.`rol_usuario` (`idrol_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`metodo_pago` (
  `idmetodo_pago` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmetodo_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `estado_venta` INT NOT NULL DEFAULT '1',
  `total` DOUBLE NOT NULL DEFAULT '0',
  `id_vendedor` INT NOT NULL,
  `metodo_de_pago` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  UNIQUE INDEX `idventa_UNIQUE` (`idventa` ASC),
  INDEX `estado_venta_idx` (`estado_venta` ASC),
  INDEX `id_vendedor_idx` (`id_vendedor` ASC),
  INDEX `metodo_de_pago_idx` (`metodo_de_pago` ASC),
  INDEX `id_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `estado_venta`
    FOREIGN KEY (`estado_venta`)
    REFERENCES `inventario`.`estados` (`idestados`),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `inventario`.`cliente` (`idcliente`),
  CONSTRAINT `id_vendedor`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `inventario`.`usuario` (`idusuario`),
  CONSTRAINT `metodo_de_pago`
    FOREIGN KEY (`metodo_de_pago`)
    REFERENCES `inventario`.`metodo_pago` (`idmetodo_pago`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`detalle_venta` (
  `id_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `t6` INT NOT NULL,
  `t8` INT NOT NULL,
  `t10` INT NOT NULL,
  `t12` INT NOT NULL,
  `t14` INT NOT NULL,
  `t16` INT NOT NULL,
  `t18` INT NOT NULL,
  `t20` INT NOT NULL,
  `t22` INT NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  PRIMARY KEY (`id_venta`, `id_producto`),
  INDEX `id_venta_idx` (`id_venta` ASC),
  INDEX `id_producto_idx` (`id_producto` ASC),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventario`.`producto` (`idproducto`),
  CONSTRAINT `id_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `inventario`.`venta` (`idventa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`perdida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`perdida` (
  `idperdida` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `t6` INT NOT NULL,
  `t8` INT NOT NULL,
  `t10` INT NOT NULL,
  `t12` INT NOT NULL,
  `t14` INT NOT NULL,
  `t16` INT NOT NULL,
  `t18` INT NOT NULL,
  `t20` INT NOT NULL,
  `t22` INT NOT NULL,
  `valor_perdida` DOUBLE NOT NULL,
  `fecha_perdida` DATE NOT NULL,
  PRIMARY KEY (`idperdida`),
  UNIQUE INDEX `idperdida_UNIQUE` (`idperdida` ASC),
  INDEX `id_producto_perdido_idx` (`id_producto` ASC),
  INDEX `id_perdida` (`id_venta` ASC),
  CONSTRAINT `id_perdida`
    FOREIGN KEY (`id_venta`)
    REFERENCES `inventario`.`venta` (`idventa`),
  CONSTRAINT `id_producto_perdido`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventario`.`producto` (`idproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
